/* ============================================
   IZA WORKOUT — Entrenos Express
   Single-session workouts organized by category
   ============================================ */

const EXPRESS_CATEGORIES = [
  { id: 'HIIT',          name: 'HIIT',            emoji: '🔥' },
  { id: 'FULL BODY',     name: 'Full Body',       emoji: '💪' },
  { id: 'POR PARTES',    name: 'Por Partes',      emoji: '🎯' },
  { id: 'CALISTENIA',    name: 'Calistenia',      emoji: '🤸' },
  { id: 'KETTLEBELL',    name: 'Kettlebell',      emoji: '⚡' },
  { id: 'MOVILIDAD',     name: 'Movilidad',       emoji: '🧘' },
  { id: 'ESTIRAMIENTOS', name: 'Estiramientos',   emoji: '🕊️' }
];

const EXPRESS_WORKOUTS = {

  /* ══════════════ HIIT ══════════════ */

  hiit_1_0: {
    id: 'hiit_1_0', name: 'HIIT 1.0', category: 'HIIT', type: 'strength',
    description: 'Bloques A y B — 40s trabajo / 20s descanso',
    muscleGroups: ['HIIT', 'Full Body'],
    exercises: [
      _ex('hiit_1_0_ex1',  'Movilidad | Cat camel', 1, '12', 0,
        'A cuatro patas, alterna arqueando la espalda hacia arriba (gato) y hundiéndola hacia abajo (camello) de forma lenta y controlada.'),
      _ex('hiit_1_0_ex2',  'Movilidad | Rotación de columna en T', 2, '12', 0,
        'Tumbado de lado con rodillas flexionadas, abre el brazo de arriba rotando el pecho hacia atrás formando una T, sin mover la cadera.'),
      _ex('hiit_1_0_ex3',  'Movilidad | Runners lunge', 2, '12/lado', 0,
        'En zancada profunda con la rodilla trasera apoyada, empuja la cadera hacia el suelo manteniendo el torso erguido para estirar el flexor de cadera.'),
      _ex('hiit_1_0_ex4',  'Zancadas sin peso', 2, '12/lado', 0,
        'Da un paso largo y baja hasta que la rodilla trasera casi toque el suelo, manteniendo el torso erguido; empuja con el talón delantero para volver a la posición inicial.'),
      _ex('hiit_1_0_ex5',  'Subidas al cajón', 2, '40s', 20, 'BLOQUE A'),
      _ex('hiit_1_0_ex6',  'Kettlebell swing', 2, '40s', 20, 'BLOQUE A'),
      _ex('hiit_1_0_ex7',  'Plancha con toques de hombro', 2, '40s', 20, 'BLOQUE A'),
      _ex('hiit_1_0_ex8',  'HIIT | Sprint estático', 2, '40s', 60, 'BLOQUE A — 3 min entre bloques'),
      _ex('hiit_1_0_ex9',  'Saltos laterales al cajón', 2, '40s', 20, 'BLOQUE B'),
      _ex('hiit_1_0_ex10', 'Sentadilla kettlebell + remo al mentón', 2, '40s', 20, 'BLOQUE B'),
      _ex('hiit_1_0_ex11', 'Core | Butterfly Sit up', 2, '40s', 20, 'BLOQUE B'),
      _ex('hiit_1_0_ex12', 'HIIT | Sprint estático', 2, '40s', 60, 'BLOQUE B'),
    ]
  },

  hiit_2_0: {
    id: 'hiit_2_0', name: 'HIIT 2.0', category: 'HIIT', type: 'strength',
    description: '3 rondas — 30s / 15s',
    muscleGroups: ['HIIT', 'Full Body'],
    exercises: [
      _ex('hiit_2_0_ex1',  'Movilidad | Flexión de tobillo de rodillas', 2, '10', 0,
        'De rodillas, empuja la cadera hacia atrás sentándote sobre el talón mientras el pie se mantiene plano en el suelo.'),
      _ex('hiit_2_0_ex2',  'Movilidad | Flexiones escapulares', 2, '10', 0,
        'En posición de plancha o cuadrupedia, junta y separa los omóplatos manteniendo los brazos extendidos, sin flexionar los codos.'),
      _ex('hiit_2_0_ex3',  'Movilidad | Supermans', 2, '10', 0,
        'Boca abajo, eleva brazos y piernas al mismo tiempo apretando glúteos y espalda, sin generar un rebote brusco.'),
      _ex('hiit_2_0_ex4',  'HIIT | Burpees', 3, '30s', 15,
        'Baja a sentadilla, apoya las manos, salta los pies atrás en plancha, haz una flexión, recupera los pies con un salto y termina con un salto vertical.'),
      _ex('hiit_2_0_ex5',  'HIIT | Sentadilla + paso atrás', 3, '30s', 15,
        'Baja a sentadilla y al subir da un paso atrás con una pierna, volviendo a la posición inicial antes de la siguiente repetición.'),
      _ex('hiit_2_0_ex6',  'HIIT | Plank thrust', 3, '30s', 15,
        'Desde plancha alta, salta llevando ambos pies hacia las manos y luego vuelve a estirarlos atrás, manteniendo la cadera estable durante el movimiento.'),
      _ex('hiit_2_0_ex7',  'HIIT | Explosive jumping jacks', 3, '30s', 15,
        'Salta abriendo piernas y brazos con máxima explosividad como en unos jumping jacks normales, pero impulsando el salto lo más alto posible.'),
      _ex('hiit_2_0_ex8',  'HIIT | Prisioner squat + knee in', 3, '30s', 15,
        'Con las manos detrás de la cabeza, baja a sentadilla y al subir lleva una rodilla hacia el pecho en equilibrio, alternando lados.'),
      _ex('hiit_2_0_ex9',  'Core | Crunch', 3, '30s', 15,
        'Tumbado con rodillas flexionadas, sube solo la parte alta de la espalda contrayendo el abdomen, sin tirar del cuello con las manos. Baja controlado sin apoyar de golpe.'),
      _ex('hiit_2_0_ex10', 'Vuelta a la calma | Trote suave', 1, '5 min', 0, 'Bajar pulsaciones'),
      _ex('hiit_2_0_ex11', 'Estiramiento | Cadera (Frog)', 1, '12', 0,
        'A cuatro patas, separa las rodillas hacia los lados y lleva la cadera hacia atrás manteniendo los tobillos flexionados, hasta sentir tensión en la ingle.'),
      _ex('hiit_2_0_ex12', 'Estiramiento | Hombros', 1, '12', 0,
        'Cruza un brazo por delante del pecho y presiona suavemente con el otro brazo hasta sentir tensión en la parte trasera del hombro.'),
      _ex('hiit_2_0_ex13', 'Estiramiento | Rodilla al pecho', 1, '12', 0,
        'Tumbada boca arriba, abraza una rodilla y llévala hacia el pecho manteniendo la otra pierna estirada o apoyada en el suelo.'),
    ]
  },

  hiit_3_0: {
    id: 'hiit_3_0', name: 'HIIT 3.0', category: 'HIIT', type: 'strength',
    description: 'HIIT Olímpico — 3 rondas 35s / 10s',
    muscleGroups: ['HIIT', 'Full Body'],
    exercises: [
      _ex('hiit_3_0_ex1',  'Movilidad | Flexiones escapulares', 2, '10', 0,
        'En posición de plancha o cuadrupedia, junta y separa los omóplatos manteniendo los brazos extendidos, sin flexionar los codos.'),
      _ex('hiit_3_0_ex2',  'Movilidad | Runners lunge with reach', 2, '6/lado', 0,
        'En zancada profunda, además de empujar la cadera hacia el suelo, eleva el brazo del lado de la pierna adelantada rotando el tronco hacia arriba.'),
      _ex('hiit_3_0_ex3',  'Movilidad | Standing reach down fwd-back', 2, '8', 0,
        'De pie, inclínate llevando las manos hacia el suelo por delante y luego arquéate suavemente hacia atrás, con control.'),
      _ex('hiit_3_0_ex4',  'HIIT | Fast feet', 3, '35s', 10,
        'Con rodillas ligeramente flexionadas, mueve los pies muy rápido tocando el suelo con la punta, como corriendo en el sitio a máxima velocidad.'),
      _ex('hiit_3_0_ex5',  'Flexiones de diamante', 3, '35s', 10,
        'Junta las manos bajo el pecho formando un diamante con los dedos. Baja controlado con los codos cerca del cuerpo para enfatizar el trabajo de tríceps.'),
      _ex('hiit_3_0_ex6',  'HIIT | Lateral lunge drop', 3, '35s', 10,
        'Desde de pie, da un paso lateral cayendo en zancada lateral con la cadera atrás y vuelve a la posición inicial con un impulso rápido.'),
      _ex('hiit_3_0_ex7',  'HIIT | Scissor jumps', 3, '35s', 10,
        'Salta alternando las piernas adelante y atrás como una tijera en el aire, aterrizando con control y cambiando de pierna en cada salto.'),
      _ex('hiit_3_0_ex8',  'Sentadilla isométrica', 3, '35s', 10,
        'Baja en sentadilla hasta el ángulo indicado y mantén la posición estática sin moverte, con el peso repartido en todo el pie y la espalda recta.'),
      _ex('hiit_3_0_ex9',  'Vuelta a la calma | Trote suave', 1, '3-5 min', 0,
        'Mantén un trote muy ligero y cómodo, con pasos cortos y respiración controlada, para ir bajando la intensidad de forma progresiva.'),
      _ex('hiit_3_0_ex10', 'Estiramiento | Cuello', 1, '10', 0,
        'Inclina la cabeza suavemente hacia un lado ayudando con la mano, sin subir el hombro contrario, hasta notar tensión suave en el lateral del cuello.'),
      _ex('hiit_3_0_ex11', 'Estiramiento | Rodilla al pecho', 1, '10', 0,
        'Tumbada boca arriba, abraza una rodilla y llévala hacia el pecho manteniendo la otra pierna estirada o apoyada en el suelo.'),
    ]
  },

  hiit_4_0: {
    id: 'hiit_4_0', name: 'HIIT 4.0', category: 'HIIT', type: 'strength',
    description: 'Piernas a fuego — 3 rondas 30s / 15s',
    muscleGroups: ['HIIT', 'Piernas'],
    exercises: [
      _ex('hiit_4_0_ex1',  'Movilidad | Bisagra de cadera', 2, '10', 0,
        'Con las rodillas ligeramente flexionadas, empuja la cadera hacia atrás manteniendo la espalda recta hasta sentir el estiramiento en los isquiotibiales.'),
      _ex('hiit_4_0_ex2',  'Movilidad | Flexión de tobillo de rodillas', 2, '10', 0,
        'De rodillas, empuja la cadera hacia atrás sentándote sobre el talón mientras el pie se mantiene plano en el suelo.'),
      _ex('hiit_4_0_ex3',  'Movilidad | Patada de glúteo de lado a lado', 2, '10', 0,
        'Boca abajo con las rodillas flexionadas, abre las piernas hacia los lados como una patada, manteniendo la pelvis fija en el suelo.'),
      _ex('hiit_4_0_ex4',  'HIIT | Sprint estático', 3, '30s', 15,
        'Corre en el sitio elevando las rodillas al máximo y moviendo los brazos con fuerza, manteniendo el tronco erguido y el ritmo alto.'),
      _ex('hiit_4_0_ex5',  'HIIT | Lateral lunge drop', 3, '30s', 15,
        'Desde de pie, da un paso lateral cayendo en zancada lateral con la cadera atrás y vuelve a la posición inicial con un impulso rápido.'),
      _ex('hiit_4_0_ex6',  'HIIT | Pulse jump squats', 3, '30s', 15,
        'Baja a sentadilla y realiza pequeños rebotes de pulso antes de saltar hacia arriba, aterrizando de nuevo en sentadilla amortiguada.'),
      _ex('hiit_4_0_ex7',  'HIIT | Plank thrust', 3, '30s', 15,
        'Desde plancha alta, salta llevando ambos pies hacia las manos y luego vuelve a estirarlos atrás, manteniendo la cadera estable durante el movimiento.'),
      _ex('hiit_4_0_ex8',  'HIIT | Sentadilla + toques de pie', 3, '30s', 15,
        'Baja a sentadilla y al subir toca el suelo lateralmente con la punta del pie contrario antes de volver a bajar, alternando lados.'),
      _ex('hiit_4_0_ex9',  'Glute bridge unilateral', 3, '30s', 15,
        'Tumbado boca arriba, una pierna extendida al aire y el otro pie apoyado, empuja con el talón de apoyo para elevar la cadera manteniéndola nivelada.'),
      _ex('hiit_4_0_ex10', 'Core | Crunch', 3, '30s', 15,
        'Tumbado con rodillas flexionadas, sube solo la parte alta de la espalda contrayendo el abdomen, sin tirar del cuello con las manos. Baja controlado sin apoyar de golpe.'),
      _ex('hiit_4_0_ex11', 'Estiramiento | Cadera (Frog)', 2, '10', 0,
        'A cuatro patas, separa las rodillas hacia los lados y lleva la cadera hacia atrás manteniendo los tobillos flexionados, hasta sentir tensión en la ingle.'),
      _ex('hiit_4_0_ex12', 'Estiramiento | Espalda', 2, '10', 0,
        'Sentada o de rodillas, redondea la espalda llevando los brazos al frente y el pecho hacia el suelo, dejando que la zona dorsal se estire pasivamente.'),
    ]
  },

  hiit_5_0: {
    id: 'hiit_5_0', name: 'HIIT 5.0', category: 'HIIT', type: 'strength',
    description: '4 rondas — 30s / 10s',
    muscleGroups: ['HIIT', 'Full Body'],
    exercises: [
      _ex('hiit_5_0_ex1',  'Movilidad | Bisagra de cadera', 2, '10', 0,
        'Con las rodillas ligeramente flexionadas, empuja la cadera hacia atrás manteniendo la espalda recta hasta sentir el estiramiento en los isquiotibiales.'),
      _ex('hiit_5_0_ex2',  'Movilidad | Rotación de columna en T', 2, '10', 0,
        'Tumbado de lado con rodillas flexionadas, abre el brazo de arriba rotando el pecho hacia atrás formando una T, sin mover la cadera.'),
      _ex('hiit_5_0_ex3',  'Movilidad | Supermans', 2, '10', 0,
        'Boca abajo, eleva brazos y piernas al mismo tiempo apretando glúteos y espalda, sin generar un rebote brusco.'),
      _ex('hiit_5_0_ex4',  'HIIT | Prisioner side to side squats', 4, '30s', 10,
        'Con las manos detrás de la cabeza, da un paso lateral a sentadilla, vuelve al centro y repite hacia el otro lado, sin dejar caer el pecho.'),
      _ex('hiit_5_0_ex5',  'HIIT | Burpees', 4, '30s', 10,
        'Baja a sentadilla, apoya las manos, salta los pies atrás en plancha, haz una flexión, recupera los pies con un salto y termina con un salto vertical.'),
      _ex('hiit_5_0_ex6',  'HIIT | Sentadilla con salto + rotación', 4, '30s', 10,
        'Baja a sentadilla y salta girando el cuerpo hacia un lado en el aire, aterrizando en sentadilla y alternando la dirección del giro.'),
      _ex('hiit_5_0_ex7',  'Core | Kick sits', 4, '30s', 10,
        'Desde sentado con piernas elevadas, extiende y flexiona alternando piernas como una patada de tijera, manteniendo el equilibrio con el abdomen. No dejes que la espalda se redondee en exceso.'),
      _ex('hiit_5_0_ex8',  'HIIT | Lunge drop', 4, '30s', 10,
        'Desde de pie, deja caer una pierna atrás hasta zancada baja tocando casi la rodilla en el suelo y vuelve a subir rápido a la posición inicial.'),
      _ex('hiit_5_0_ex9',  'HIIT | Sprint estático', 4, '30s', 10,
        'Corre en el sitio elevando las rodillas al máximo y moviendo los brazos con fuerza, manteniendo el tronco erguido y el ritmo alto.'),
      _ex('hiit_5_0_ex10', 'Estiramiento | Glúteo medio', 2, '10', 0,
        'Tumbada boca arriba, cruza un tobillo sobre la rodilla contraria y tira de esa pierna hacia el pecho hasta sentir tensión en el glúteo.'),
      _ex('hiit_5_0_ex11', 'Estiramiento | Rodilla al pecho', 2, '10', 0,
        'Tumbada boca arriba, abraza una rodilla y llévala hacia el pecho manteniendo la otra pierna estirada o apoyada en el suelo.'),
    ]
  },

  hiit_abs: {
    id: 'hiit_abs', name: 'HIIT Abs', category: 'HIIT', type: 'strength',
    description: 'The sound of the summer is CRUNCH — 2 rondas 35s / 15s',
    muscleGroups: ['Core', 'HIIT'],
    exercises: [
      _ex('hiit_abs_ex1',  'Movilidad | Cat camel', 2, '10', 0,
        'A cuatro patas, alterna arqueando la espalda hacia arriba (gato) y hundiéndola hacia abajo (camello) de forma lenta y controlada.'),
      _ex('hiit_abs_ex2',  'Movilidad | Hip CAR', 2, '10', 0,
        'Apoyado en una pared, dibuja el círculo más amplio posible con la pierna manteniendo la cadera estable, sin mover el tronco.'),
      _ex('hiit_abs_ex3',  'Movilidad | Rotación de hombro de rodillas', 2, '10', 0,
        'De rodillas con una mano apoyada, rota el brazo libre hacia arriba abriendo el pecho y sigue el movimiento con la mirada.'),
      _ex('hiit_abs_ex4',  'HIIT | Jumping jacks', 2, '35s', 15,
        'Salta abriendo piernas y brazos a la vez hacia los lados y vuelve a juntarlos al aterrizar, manteniendo un ritmo constante y rodillas suaves.'),
      _ex('hiit_abs_ex5',  'Core | McGuill crunch', 2, '35s', 15,
        'Tumbado con una pierna flexionada y la otra extendida, coloca las manos bajo la zona lumbar y eleva ligeramente los hombros del suelo sin flexionar la columna. El movimiento es mínimo, no un crunch completo.'),
      _ex('hiit_abs_ex6',  'Core | Scissors', 2, '35s', 15,
        'Tumbado con la zona lumbar pegada al suelo, eleva ligeramente las piernas rectas y cruza una sobre otra en tijera continua. No dejes que la espalda se arquee.'),
      _ex('hiit_abs_ex7',  'Core | Mountain climbers + toques de rodilla', 2, '35s', 15,
        'Desde plancha alta, lleva la rodilla hacia el pecho y añade un pequeño toque antes de volver a extender la pierna, alternando lados. Mantén la cadera baja y estable.'),
      _ex('hiit_abs_ex8',  'Core | Plancha de codos a manos', 2, '35s', 15,
        'Empieza en plancha de antebrazos y sube uno a uno los brazos hasta plancha alta, luego baja de nuevo, sin mover la cadera de lado a lado. Mantén el core firme en todo momento.'),
      _ex('hiit_abs_ex9',  'Core | V ups', 2, '35s', 15,
        'Tumbado con brazos y piernas extendidos, sube ambos a la vez para formar una V tocando manos con pies. Baja controlado sin dejar caer piernas y tronco de golpe.'),
      _ex('hiit_abs_ex10', 'Core | Deadbugs', 2, '35s', 15,
        'Tumbado con brazos y piernas en el aire a 90º, extiende brazo y pierna opuestos hacia el suelo sin que la lumbar se despegue. Vuelve al centro y alterna de lado.'),
      _ex('hiit_abs_ex11', 'Estiramiento | Espalda', 2, '12', 0,
        'Sentada o de rodillas, redondea la espalda llevando los brazos al frente y el pecho hacia el suelo, dejando que la zona dorsal se estire pasivamente.'),
      _ex('hiit_abs_ex12', 'Estiramiento | Rodilla al pecho', 2, '12', 0,
        'Tumbada boca arriba, abraza una rodilla y llévala hacia el pecho manteniendo la otra pierna estirada o apoyada en el suelo.'),
    ]
  },

  hiit_abs_sm: {
    id: 'hiit_abs_sm', name: 'HIIT Abs sin Material', category: 'HIIT', type: 'strength',
    description: '3 circuitos — Tábata final 20s / 10s',
    muscleGroups: ['Core', 'HIIT'],
    exercises: [
      _ex('hiit_abs_sm_ex1',  'Core | Deadbugs', 2, '40s', 20, 'Circuito 1'),
      _ex('hiit_abs_sm_ex2',  'Hip dips plank', 2, '40s', 20, 'Circuito 1'),
      _ex('hiit_abs_sm_ex3',  'Core | Zombie sit ups', 2, '40s', 20, 'Circuito 1'),
      _ex('hiit_abs_sm_ex4',  'Core | Jumping jacks plank', 2, '40s', 20, 'Circuito 1'),
      _ex('hiit_abs_sm_ex5',  'Plank toe tap', 2, '40s', 20, 'Circuito 2'),
      _ex('hiit_abs_sm_ex6',  'Core | Hollow hold', 2, '40s', 20, 'Circuito 2'),
      _ex('hiit_abs_sm_ex7',  'Core | Mountain climbers', 2, '40s', 20, 'Circuito 2'),
      _ex('hiit_abs_sm_ex8',  'Core | Bear crawl', 2, '40s', 20, 'Circuito 2'),
      _ex('hiit_abs_sm_ex9',  'Core | Knee to toe taps', 4, '20s', 10, 'TÁBATA FINAL'),
      _ex('hiit_abs_sm_ex10', 'HIIT | Jumping jacks', 4, '20s', 10, 'TÁBATA FINAL'),
    ]
  },

  hiit_gluteos_kb: {
    id: 'hiit_gluteos_kb', name: 'HIIT Glúteos con Kettlebell', category: 'HIIT', type: 'strength',
    description: 'Booty Day en casita — 4 rondas 35s / 15s',
    muscleGroups: ['Glúteos', 'HIIT'],
    exercises: [
      _ex('hiit_gkb_ex1',  'Movilidad | Rotación interna cadera 90-90', 2, '8/lado', 0,
        'Sentado con ambas piernas flexionadas a 90 grados hacia el mismo lado, rota las rodillas hacia el lado contrario manteniendo la espalda recta.'),
      _ex('hiit_gkb_ex2',  'Movilidad | Balanceo de piernas', 2, '8/lado', 0,
        'De pie con apoyo, balancea una pierna hacia delante y atrás con control, sin dejar que la cadera compense el movimiento.'),
      _ex('hiit_gkb_ex3',  'Movilidad | Frog Rolls', 2, '10', 0,
        'Boca arriba con las rodillas abiertas y plantas de los pies juntas, rueda de lado a lado manteniendo la posición de rana.'),
      _ex('hiit_gkb_ex4',  'Movilidad | Movimientos escapulares', 2, '8', 0,
        'En posición de plancha o cuadrupedia, junta y separa los omóplatos manteniendo los brazos extendidos, sin flexionar los codos.'),
      _ex('hiit_gkb_ex5',  'Sentadilla goblet con doble pausa', 4, '35s', 15,
        'Sujeta el peso contra el pecho y baja en sentadilla haciendo una pausa a mitad de camino y otra en el punto más bajo antes de subir con control.'),
      _ex('hiit_gkb_ex6',  'Peso muerto con kettlebell y resistencia', 4, '35s', 15,
        'Sujeta la kettlebell entre las piernas con la goma bajo los pies; baja con bisagra de cadera y espalda neutra, subiendo con glúteos.'),
      _ex('hiit_gkb_ex7',  'Hip thrust con mancuerna', 4, '35s/pierna', 15,
        'Con una mancuerna apoyada sobre la cadera con las manos, empuja con los talones extendiendo la cadera por completo y aprieta el glúteo arriba.'),
      _ex('hiit_gkb_ex8',  'Sentadilla búlgara goblet', 4, '35s/pierna', 15,
        'Pie trasero apoyado en un banco, sujeta la mancuerna o disco a la altura del pecho con ambas manos y baja con la pierna delantera hasta casi paralelo.'),
      _ex('hiit_gkb_ex9',  'Kettlebell swing', 4, '35s', 15,
        'Con la kettlebell entre las piernas, impulsa desde la cadera hacia atrás y adelante, sin usar los brazos para levantarla ni flexionar mucho las rodillas.'),
      _ex('hiit_gkb_ex10', 'Vuelta a la calma | Trote suave', 1, '3-5 min', 0,
        'Mantén un trote muy ligero y cómodo, con pasos cortos y respiración controlada, para ir bajando la intensidad de forma progresiva.'),
      _ex('hiit_gkb_ex11', 'Estiramiento | Espalda', 1, '10', 0,
        'Sentada o de rodillas, redondea la espalda llevando los brazos al frente y el pecho hacia el suelo, dejando que la zona dorsal se estire pasivamente.'),
      _ex('hiit_gkb_ex12', 'Estiramiento | Piramidal', 1, '10', 0,
        'Tumbada boca arriba, cruza un tobillo sobre la rodilla contraria y tira de esa pierna hacia el pecho hasta sentir tensión profunda en el glúteo.'),
      _ex('hiit_gkb_ex13', 'Estiramientos circulares', 1, '10', 0,
        'Realiza círculos amplios y controlados con la articulación indicada, aumentando poco a poco el rango sin forzar ni sentir dolor.'),
    ]
  },

  hiit_tren_sup: {
    id: 'hiit_tren_sup', name: 'HIIT Tren Superior', category: 'HIIT', type: 'strength',
    description: 'Un kettlebell y magia — 3 rondas 30s / 15s',
    muscleGroups: ['Tren superior', 'HIIT'],
    exercises: [
      _ex('hiit_ts_ex1',  'Movilidad | Shoulder CAR', 2, '8', 0,
        'De pie o sentado, dibuja el círculo más amplio posible con el brazo controlando cada fase del movimiento sin compensar con el tronco.'),
      _ex('hiit_ts_ex2',  'Movilidad | Cat camel', 2, '10', 0,
        'A cuatro patas, alterna arqueando la espalda hacia arriba (gato) y hundiéndola hacia abajo (camello) de forma lenta y controlada.'),
      _ex('hiit_ts_ex3',  "Movilidad | WGS (World's Greatest Stretch)", 2, '8/lado', 0,
        'Desde zancada profunda, apoya la mano interior en el suelo y rota el tronco abriendo el brazo contrario hacia el techo, siguiendo con la mirada.'),
      _ex('hiit_ts_ex4',  'Movilidad | Supermans', 2, '10', 0,
        'Boca abajo, eleva brazos y piernas al mismo tiempo apretando glúteos y espalda, sin generar un rebote brusco.'),
      _ex('hiit_ts_ex5',  'Progresión | Flexiones', 3, '30s', 15,
        'Elige la variante de flexión adecuada a tu nivel (con apoyo en rodillas o pared si es necesario) manteniendo el cuerpo en línea recta y bajando el pecho controlado.'),
      _ex('hiit_ts_ex6',  'Press de hombro unilateral de rodillas', 3, '30s (15s/lado)', 15,
        'Desde la posición de rodillas, empuja una mancuerna desde el hombro hacia arriba manteniendo el core firme y sin inclinar el tronco.'),
      _ex('hiit_ts_ex7',  'Remo unilateral con mancuernas', 3, '30s (15s/lado)', 15,
        'Con una mano y una rodilla apoyadas en el banco, tira de la mancuerna hacia la cadera llevando el codo atrás, sin rotar el tronco.'),
      _ex('hiit_ts_ex8',  'Curl de bíceps con mancuerna', 3, '30s', 15,
        'De pie o sentado, flexiona el codo llevando la mancuerna hacia el hombro sin balancear el tronco. Mantén el codo pegado al cuerpo durante todo el recorrido.'),
      _ex('hiit_ts_ex9',  'Fondos de tríceps en banco', 3, '30s', 15,
        'Manos en el borde del banco, piernas extendidas o flexionadas al frente, baja el cuerpo flexionando los codos hacia atrás hasta 90° y empuja para subir.'),
      _ex('hiit_ts_ex10', 'Elevaciones unilaterales', 3, '30s (15s/lado)', 15,
        'Eleva un brazo a la vez hasta la altura del hombro liderando con el codo, controlando la bajada sin balancear el tronco.'),
      _ex('hiit_ts_ex11', 'Vuelta a la calma | Trote suave', 1, '3-5 min', 0,
        'Mantén un trote muy ligero y cómodo, con pasos cortos y respiración controlada, para ir bajando la intensidad de forma progresiva.'),
      _ex('hiit_ts_ex12', 'Estiramiento | Cuello', 1, '10', 30,
        'Inclina la cabeza suavemente hacia un lado ayudando con la mano, sin subir el hombro contrario, hasta notar tensión suave en el lateral del cuello.'),
      _ex('hiit_ts_ex13', 'Estiramiento | Hombros con rotación', 1, '10', 30,
        'Cruza un brazo por delante del pecho y añade una ligera rotación de tronco hacia el lado contrario para ampliar el estiramiento del hombro.'),
      _ex('hiit_ts_ex14', 'Estiramiento | Muñecas', 1, '10', 30,
        'Extiende el brazo con la palma hacia arriba o abajo y tira suavemente de los dedos hacia atrás con la otra mano hasta sentir tensión en el antebrazo.'),
    ]
  },

  /* ══════════════ FULL BODY ══════════════ */

  fb_casa: {
    id: 'fb_casa', name: 'Full Body Casa', category: 'FULL BODY', type: 'strength',
    description: 'Fullbody con banco/silla — 2 circuitos + Tábata',
    muscleGroups: ['Full Body'],
    exercises: [
      _ex('fb_casa_ex1',  'Reverse lunge con mancuernas', 2, '40s', 20, 'Circuito 1'),
      _ex('fb_casa_ex2',  'Fondos de tríceps en banco', 2, '40s', 20, 'Circuito 1'),
      _ex('fb_casa_ex3',  'Core | Deadbugs', 2, '40s alternando', 20, 'Circuito 1'),
      _ex('fb_casa_ex4',  'Core | Plancha de codos a manos', 2, '40s', 20, 'Circuito 1'),
      _ex('fb_casa_ex5',  'Sentadilla + Curtsy lunge', 2, '40s', 20, 'Circuito 2'),
      _ex('fb_casa_ex6',  'Core | Plancha', 2, '40s', 20, 'Circuito 2'),
      _ex('fb_casa_ex7',  'Puente de glúteos unilateral (izq)', 2, '40s', 20, 'Circuito 2'),
      _ex('fb_casa_ex8',  'Puente de glúteos unilateral (der)', 2, '40s', 20, 'Circuito 2'),
      _ex('fb_casa_ex9',  'HIIT | Burpee sin salto', 4, '20s', 10, 'Tábata final'),
      _ex('fb_casa_ex10', 'Core | Cocoons', 4, '20s', 10, 'Tábata final'),
    ]
  },

  fb_gomas: {
    id: 'fb_gomas', name: 'Full Body con Gomas', category: 'FULL BODY', type: 'strength',
    description: '3 rondas — 35s / 10s',
    muscleGroups: ['Full Body'],
    exercises: [
      _ex('fb_gomas_ex1',  'Movilidad | Rotación interna cadera 90-90', 2, '8/lado', 0,
        'Sentado con ambas piernas flexionadas a 90 grados hacia el mismo lado, rota las rodillas hacia el lado contrario manteniendo la espalda recta.'),
      _ex('fb_gomas_ex2',  'Movilidad | Cat camel', 2, '10', 0,
        'A cuatro patas, alterna arqueando la espalda hacia arriba (gato) y hundiéndola hacia abajo (camello) de forma lenta y controlada.'),
      _ex('fb_gomas_ex3',  'Movilidad | Frog Rolls', 2, '10', 0,
        'Boca arriba con las rodillas abiertas y plantas de los pies juntas, rueda de lado a lado manteniendo la posición de rana.'),
      _ex('fb_gomas_ex4',  'Movilidad | Rotación de columna en T', 2, '8/lado', 0,
        'Tumbado de lado con rodillas flexionadas, abre el brazo de arriba rotando el pecho hacia atrás formando una T, sin mover la cadera.'),
      _ex('fb_gomas_ex5',  'Peso muerto con resistencia', 3, '35s', 10,
        'Pisa la goma y sujeta los extremos; realiza una bisagra de cadera con espalda neutra, subiendo con el empuje de glúteos.'),
      _ex('fb_gomas_ex6',  'Press pecho unilateral en decúbito', 3, '35s', 10,
        'Tumbado, empuja una mancuerna hacia arriba desde el pecho con un solo brazo, controlando que el tronco no gire.'),
      _ex('fb_gomas_ex7',  'Remo gironda con resistencia', 3, '35s', 10,
        'Sentado con las piernas semiflexionadas, tira de la goma hacia el abdomen llevando los codos atrás, sin balancear el tronco.'),
      _ex('fb_gomas_ex8',  'Sentadilla búlgara con resistencia', 3, '35s', 10,
        'Pie trasero apoyado en un banco y banda de resistencia bajo el pie delantero sujeta con las manos; baja con la pierna delantera sintiendo la tensión constante.'),
      _ex('fb_gomas_ex9',  'Extensión de tríceps con resistencia', 3, '35s', 10,
        'Con la goma anclada arriba y sujeta con ambas manos, extiende los codos hacia abajo o al frente manteniéndolos fijos junto al cuerpo.'),
      _ex('fb_gomas_ex10', 'Curl de bíceps + press con resistencia', 3, '35s', 10,
        'Con la goma bajo los pies, haz un curl de bíceps y al llegar arriba continúa empujando hacia el techo en press de hombro. Baja controlado invirtiendo la secuencia.'),
      _ex('fb_gomas_ex11', 'Vuelta a la calma | Trote suave', 1, '3-5 min', 0,
        'Mantén un trote muy ligero y cómodo, con pasos cortos y respiración controlada, para ir bajando la intensidad de forma progresiva.'),
      _ex('fb_gomas_ex12', 'Estiramiento | Cadera (Frog)', 1, '10', 30,
        'A cuatro patas, separa las rodillas hacia los lados y lleva la cadera hacia atrás manteniendo los tobillos flexionados, hasta sentir tensión en la ingle.'),
      _ex('fb_gomas_ex13', 'Estiramiento | Hombros', 1, '10', 30,
        'Cruza un brazo por delante del pecho y presiona suavemente con el otro brazo hasta sentir tensión en la parte trasera del hombro.'),
      _ex('fb_gomas_ex14', 'Estiramiento | Rodilla al pecho', 1, '10', 30,
        'Tumbada boca arriba, abraza una rodilla y llévala hacia el pecho manteniendo la otra pierna estirada o apoyada en el suelo.'),
    ]
  },

  fb_gomas_kb: {
    id: 'fb_gomas_kb', name: 'Full Body con Gomas y Kettlebell', category: 'FULL BODY', type: 'strength',
    description: 'No excuses! — 3 rondas 30s / 15s',
    muscleGroups: ['Full Body'],
    exercises: [
      _ex('fb_gkb_ex1',  'Movilidad | Cat camel', 2, '8', 15,
        'A cuatro patas, alterna arqueando la espalda hacia arriba (gato) y hundiéndola hacia abajo (camello) de forma lenta y controlada.'),
      _ex('fb_gkb_ex2',  'Movilidad | Leg Rockback', 2, '8', 15,
        'Desde cuadrupedia, siéntate hacia atrás sobre los talones manteniendo las manos fijas para movilizar cadera y hombros.'),
      _ex('fb_gkb_ex3',  'Movilidad | Kettlebell halos', 2, '10 (5/lado)', 15,
        'Sujeta la kettlebell cerca de la cabeza y traza un círculo alrededor de ella manteniendo el tronco estable y el abdomen firme.'),
      _ex('fb_gkb_ex4',  'Movilidad | Aductores con kettlebell', 2, '10 (5/lado)', 15,
        'En sentadilla amplia, sujeta la kettlebell cerca del pecho y balancéate de lado a lado empujando la rodilla hacia fuera para abrir la cadera.'),
      _ex('fb_gkb_ex5',  'Core | Deadbugs', 1, '10 (5/lado)', 15,
        'Tumbado con brazos y piernas en el aire a 90º, extiende brazo y pierna opuestos hacia el suelo sin que la lumbar se despegue. Vuelve al centro y alterna de lado.'),
      _ex('fb_gkb_ex6',  'Peso muerto + sentadilla con kettlebell', 3, '30s', 15,
        'Encadena un peso muerto con espalda neutra a una sentadilla goblet sujetando la kettlebell pegada al pecho, sin perder la tensión del core entre ambos.'),
      _ex('fb_gkb_ex7',  'Press de pecho con resistencia tumbada', 3, '30s', 15,
        'Tumbado con la goma anclada detrás, empuja los extremos hacia arriba desde el pecho sin despegar los glúteos del suelo.'),
      _ex('fb_gkb_ex8',  'Thrusters con resistencia', 3, '30s', 15,
        'Baja en sentadilla con la banda de resistencia sujeta a la altura de los hombros y, al subir, empuja hacia arriba extendiendo los brazos por encima de la cabeza.'),
      _ex('fb_gkb_ex9',  'Kettlebell swing unilateral', 3, '30s (15s/lado)', 15,
        'Realiza el swing sujetando la kettlebell con un solo brazo, generando la fuerza desde la cadera y manteniendo el tronco estable sin rotar.'),
      _ex('fb_gkb_ex10', 'Press francés con resistencia', 3, '30s', 15,
        'Con los codos fijos apuntando al techo, extiende el antebrazo contra la resistencia de la goma sin mover los brazos de sitio.'),
      _ex('fb_gkb_ex11', 'Glute bridge unilateral', 3, '30s (15s/lado)', 15,
        'Tumbado boca arriba, una pierna extendida al aire y el otro pie apoyado, empuja con el talón de apoyo para elevar la cadera manteniéndola nivelada.'),
      _ex('fb_gkb_ex12', 'Gorilla row', 3, '30s (15s/lado)', 15,
        'Con dos mancuernas o discos en el suelo entre las piernas, cadera atrás y espalda recta, rema alternando brazos tirando del peso hacia la cadera.'),
      _ex('fb_gkb_ex13', 'Elevaciones laterales con resistencia', 3, '30s (15s/lado)', 15,
        'Con la goma bajo los pies y un extremo en cada mano, eleva los brazos hacia los lados hasta la altura del hombro sin balancear el torso.'),
      _ex('fb_gkb_ex14', 'HIIT | Explosive jumping jacks', 3, '30s', 15,
        'Salta abriendo piernas y brazos con máxima explosividad como en unos jumping jacks normales, pero impulsando el salto lo más alto posible.'),
      _ex('fb_gkb_ex15', 'Vuelta a la calma | Trote suave', 1, '3-5 min', 0,
        'Mantén un trote muy ligero y cómodo, con pasos cortos y respiración controlada, para ir bajando la intensidad de forma progresiva.'),
      _ex('fb_gkb_ex16', 'Estiramiento | Espalda en cajón', 1, '10', 15,
        'Con los pies apoyados en un cajón o banco y manos en el suelo delante, deja caer el pecho entre los brazos para estirar la espalda con más rango.'),
      _ex('fb_gkb_ex17', 'Estiramiento | Hombros con rotación', 1, '10', 15,
        'Cruza un brazo por delante del pecho y añade una ligera rotación de tronco hacia el lado contrario para ampliar el estiramiento del hombro.'),
    ]
  },

  fb_gym: {
    id: 'fb_gym', name: 'Full Body Express Gym', category: 'FULL BODY', type: 'strength',
    description: '30 minutos — poco tiempo, gran resultado',
    muscleGroups: ['Full Body'],
    exercises: [
      _ex('fb_gym_ex1',  'Movilidad | Rotación interna cadera 90-90', 1, '6/lado', 10,
        'Sentado con ambas piernas flexionadas a 90 grados hacia el mismo lado, rota las rodillas hacia el lado contrario manteniendo la espalda recta.'),
      _ex('fb_gym_ex2',  "Movilidad | WGS (World's Greatest Stretch)", 1, '6/lado', 15,
        'Desde zancada profunda, apoya la mano interior en el suelo y rota el tronco abriendo el brazo contrario hacia el techo, siguiendo con la mirada.'),
      _ex('fb_gym_ex3',  'Peso muerto convencional (aproximación)', 2, '4-6', 60, '1 min descanso'),
      _ex('fb_gym_ex4',  'Peso muerto convencional (trabajo 1)', 1, '6-8', 120,
        'En la serie de trabajo mantén la barra pegada al cuerpo, espalda neutra y empuje de piernas y glúteos para subir.'),
      _ex('fb_gym_ex5',  'Peso muerto convencional (trabajo 2)', 1, '10-12', 90, '1-2 min descanso'),
      _ex('fb_gym_ex6',  'Press banca inclinado con mancuernas', 3, '8-10', 60, 'Superserie'),
      _ex('fb_gym_ex7',  'Remo seal con mancuernas', 3, '8-10', 60, 'Superserie'),
      _ex('fb_gym_ex8',  'Sentadilla búlgara con mancuerna', 1, 'Máx (15-20)/pierna', 0, 'FALLO'),
      _ex('fb_gym_ex9',  'Curl de bíceps de pie', 2, '12-15', 0, 'Superserie'),
      _ex('fb_gym_ex10', 'Press francés', 2, '12-15', 0, 'Superserie'),
      _ex('fb_gym_ex11', 'Curl de femoral', 1, 'Máx (15-20)', 0,
        'Tumbado o sentado en la máquina, flexiona la rodilla llevando el talón hacia el glúteo sin levantar la cadera del apoyo. Vuelve controlando la carga hasta la extensión completa.'),
      _ex('fb_gym_ex12', 'Vuelta a la calma | Trote suave', 1, '5 min', 0,
        'Mantén un trote muy ligero y cómodo, con pasos cortos y respiración controlada, para ir bajando la intensidad de forma progresiva.'),
    ]
  },

  fb_mancuernas: {
    id: 'fb_mancuernas', name: 'Full Body Mancuernas', category: 'FULL BODY', type: 'strength',
    description: '2 circuitos + Tábata final',
    muscleGroups: ['Full Body'],
    exercises: [
      _ex('fb_mc_ex1',  'Sentadilla goblet con doble pausa', 2, '40s', 20, 'Circuito 1'),
      _ex('fb_mc_ex2',  'Renegade row', 2, '40s alterno', 20, 'Circuito 1'),
      _ex('fb_mc_ex3',  'Zancadas con mancuernas', 2, '40s alternando', 20, 'Circuito 1'),
      _ex('fb_mc_ex4',  'Plank toe tap', 2, '40s', 20, 'Circuito 1'),
      _ex('fb_mc_ex5',  'Thruster con mancuernas', 2, '40s', 20, 'Circuito 2'),
      _ex('fb_mc_ex6',  'Core | Russian twist con mancuerna', 2, '40s', 20, 'Circuito 2'),
      _ex('fb_mc_ex7',  'HIIT | Lateral lunge drop (izq)', 2, '40s', 20, 'Circuito 2'),
      _ex('fb_mc_ex8',  'HIIT | Lateral lunge drop (der)', 2, '40s', 20, 'Circuito 2'),
      _ex('fb_mc_ex9',  'Core | Zombie sit ups', 4, '20s', 10, 'Tábata final'),
      _ex('fb_mc_ex10', 'HIIT | Pulse jump squats', 4, '20s', 10, 'Tábata final'),
    ]
  },

  /* ══════════════ POR PARTES ══════════════ */

  pp_dominada_1: {
    id: 'pp_dominada_1', name: '1 Dominada', category: 'POR PARTES', type: 'strength',
    description: 'Progresión completa para tu primera dominada',
    muscleGroups: ['Espalda', 'Bíceps'],
    exercises: [
      _ex('pp_dom1_ex1',  'Movilidad | Prone snow angels', 2, '8', 10,
        'Boca abajo, desliza los brazos desde los costados hacia arriba de la cabeza como si hicieras un ángel de nieve, manteniendo el pecho en el suelo.'),
      _ex('pp_dom1_ex2',  'Movilidad | Shoulder CAR', 2, '8/lado', 10,
        'De pie o sentado, dibuja el círculo más amplio posible con el brazo controlando cada fase del movimiento sin compensar con el tronco.'),
      _ex('pp_dom1_ex3',  'Movilidad | Supermans', 1, '12', 10,
        'Boca abajo, eleva brazos y piernas al mismo tiempo apretando glúteos y espalda, sin generar un rebote brusco.'),
      _ex('pp_dom1_ex4',  'Remo en TRX', 2, '10-12', 120,
        'Sujeta las cintas con el cuerpo inclinado hacia atrás y tira del pecho hacia las manos llevando los codos atrás, sin dejar caer la cadera.'),
      _ex('pp_dom1_ex5',  'Australian pull-ups', 3, '2-4/5-7/8-10', 90, 'Pirámide ascendente'),
      _ex('pp_dom1_ex6',  'Remo en T', 2, '6-8/10-15', 60,
        'Con el tronco inclinado sobre la barra en T, tira hacia el abdomen llevando los codos atrás y juntando los omóplatos, sin redondear la espalda.'),
      _ex('pp_dom1_ex7',  'Gorilla row', 3, '8-12', 60,
        'Con dos mancuernas o discos en el suelo entre las piernas, cadera atrás y espalda recta, rema alternando brazos tirando del peso hacia la cadera.'),
      _ex('pp_dom1_ex8',  'Dominadas con gomas', 1, 'Máximas', 0, 'Al fallo'),
      _ex('pp_dom1_ex9',  'Estiramiento | Espalda', 2, '10', 10,
        'Sentada o de rodillas, redondea la espalda llevando los brazos al frente y el pecho hacia el suelo, dejando que la zona dorsal se estire pasivamente.'),
      _ex('pp_dom1_ex10', 'Estiramiento | Hombros', 1, '12', 10,
        'Cruza un brazo por delante del pecho y presiona suavemente con el otro brazo hasta sentir tensión en la parte trasera del hombro.'),
    ]
  },

  pp_flexion_1: {
    id: 'pp_flexion_1', name: '1 Flexión', category: 'POR PARTES', type: 'strength',
    description: 'Tu primera flexión ya la tienes y no lo sabías',
    muscleGroups: ['Pecho', 'Tríceps', 'Hombros'],
    exercises: [
      _ex('pp_flx1_ex1',  'Movilidad | Shoulder CAR', 2, '10', 30,
        'De pie o sentado, dibuja el círculo más amplio posible con el brazo controlando cada fase del movimiento sin compensar con el tronco.'),
      _ex('pp_flx1_ex2',  'Movilidad | Cat camel', 2, '10', 30,
        'A cuatro patas, alterna arqueando la espalda hacia arriba (gato) y hundiéndola hacia abajo (camello) de forma lenta y controlada.'),
      _ex('pp_flx1_ex3',  'Core | Deadbugs', 2, '12 (6/lado)', 30,
        'Tumbado con brazos y piernas en el aire a 90º, extiende brazo y pierna opuestos hacia el suelo sin que la lumbar se despegue. Vuelve al centro y alterna de lado.'),
      _ex('pp_flx1_ex4',  'Progresión | Flexiones', 1, '2', 120,
        'Elige la variante de flexión adecuada a tu nivel (con apoyo en rodillas o pared si es necesario) manteniendo el cuerpo en línea recta y bajando el pecho controlado.'),
      _ex('pp_flx1_ex5',  'Press de pecho con resistencia tumbada', 2, '10', 60,
        'Tumbado con la goma anclada detrás, empuja los extremos hacia arriba desde el pecho sin despegar los glúteos del suelo.'),
      _ex('pp_flx1_ex6',  'Press de hombro con resistencia', 2, '10', 60,
        'De pie sobre la goma, empuja los extremos desde la altura de los hombros hacia arriba sin arquear la espalda.'),
      _ex('pp_flx1_ex7',  'Extensión de tríceps con resistencia', 2, '12', 60,
        'Con la goma anclada arriba y sujeta con ambas manos, extiende los codos hacia abajo o al frente manteniéndolos fijos junto al cuerpo.'),
      _ex('pp_flx1_ex8',  'Elevaciones laterales con resistencia', 1, '8/lado', 60,
        'Con la goma bajo los pies y un extremo en cada mano, eleva los brazos hacia los lados hasta la altura del hombro sin balancear el torso.'),
      _ex('pp_flx1_ex9',  'Flexiones', 2, 'Máximas', 180,
        'Manos algo más anchas que los hombros, cuerpo en línea recta desde cabeza a talones. Baja el pecho casi hasta el suelo sin hundir la cadera y empuja hasta extender los codos.'),
      _ex('pp_flx1_ex10', 'Estiramiento | Hombros con rotación', 1, '10', 30,
        'Cruza un brazo por delante del pecho y añade una ligera rotación de tronco hacia el lado contrario para ampliar el estiramiento del hombro.'),
      _ex('pp_flx1_ex11', 'Estiramiento | Espalda', 1, '10', 30,
        'Sentada o de rodillas, redondea la espalda llevando los brazos al frente y el pecho hacia el suelo, dejando que la zona dorsal se estire pasivamente.'),
    ]
  },

  pp_dominada_2: {
    id: 'pp_dominada_2', name: '1 Dominada 2.0', category: 'POR PARTES', type: 'strength',
    description: 'Tu primera dominada ya está aquí',
    muscleGroups: ['Espalda', 'Bíceps'],
    exercises: [
      _ex('pp_dom2_ex1',  'Movilidad | Cat camel', 2, '8', 15,
        'A cuatro patas, alterna arqueando la espalda hacia arriba (gato) y hundiéndola hacia abajo (camello) de forma lenta y controlada.'),
      _ex('pp_dom2_ex2',  'Movilidad | Prone snow angels', 2, '10', 15,
        'Boca abajo, desliza los brazos desde los costados hacia arriba de la cabeza como si hicieras un ángel de nieve, manteniendo el pecho en el suelo.'),
      _ex('pp_dom2_ex3',  'Movilidad | Rotación de columna en T', 2, '10', 15,
        'Tumbado de lado con rodillas flexionadas, abre el brazo de arriba rotando el pecho hacia atrás formando una T, sin mover la cadera.'),
      _ex('pp_dom2_ex4',  'Core | Deadbugs', 2, '6/lado', 15,
        'Tumbado con brazos y piernas en el aire a 90º, extiende brazo y pierna opuestos hacia el suelo sin que la lumbar se despegue. Vuelve al centro y alterna de lado.'),
      _ex('pp_dom2_ex5',  'Dominadas negativas', 1, '5', 180,
        'Sube con ayuda o salto hasta arriba de la barra y baja lo más lenta y controlada posible, resistiendo con la espalda hasta extender los brazos.'),
      _ex('pp_dom2_ex6',  'Remo con barra a 90°', 2, '6-8', 90,
        'Con el tronco inclinado a 90 grados y espalda neutra, tira de la barra hacia el abdomen llevando los codos atrás, sin usar el impulso de la espalda.'),
      _ex('pp_dom2_ex7',  'Remo en T', 3, '8/10/12', 60, 'Pirámide descendente'),
      _ex('pp_dom2_ex8',  'Remo unilateral con mancuernas', 2, '10-12', 30,
        'Con una mano y una rodilla apoyadas en el banco, tira de la mancuerna hacia la cadera llevando el codo atrás, sin rotar el tronco.'),
      _ex('pp_dom2_ex9',  'Facepull en polea', 3, '10-15', 0, 'Al fallo'),
      _ex('pp_dom2_ex10', 'Dominadas con gomas', 2, '4-6/MAX', 60,
        'Con la goma anclada arriba y sujeta a la cadera o rodilla, tira hasta acercar el pecho a la barra, apretando escápulas antes de bajar controlada.'),
      _ex('pp_dom2_ex11', 'Estiramiento | Espalda en cajón', 1, '10', 15,
        'Con los pies apoyados en un cajón o banco y manos en el suelo delante, deja caer el pecho entre los brazos para estirar la espalda con más rango.'),
      _ex('pp_dom2_ex12', 'Estiramiento | Rodilla al pecho', 1, '10', 15,
        'Tumbada boca arriba, abraza una rodilla y llévala hacia el pecho manteniendo la otra pierna estirada o apoyada en el suelo.'),
    ]
  },

  pp_abs: {
    id: 'pp_abs', name: 'Abs Express', category: 'POR PARTES', type: 'strength',
    description: '¿Solo 30\'? Dale fuego a tus abdominales',
    muscleGroups: ['Core'],
    exercises: [
      _ex('pp_abs_ex1', 'Movilidad | Rotación de columna en cuadrupedia', 1, '10', 0,
        'A cuatro patas, lleva un brazo por debajo del cuerpo rotando la columna y luego ábrelo hacia arriba siguiendo la mano con la mirada.'),
      _ex('pp_abs_ex2', "Movilidad | WGS (World's Greatest Stretch)", 1, '10', 0,
        'Desde zancada profunda, apoya la mano interior en el suelo y rota el tronco abriendo el brazo contrario hacia el techo, siguiendo con la mirada.'),
      _ex('pp_abs_ex3', 'Movilidad | Shoulder CAR', 1, '10', 0,
        'De pie o sentado, dibuja el círculo más amplio posible con el brazo controlando cada fase del movimiento sin compensar con el tronco.'),
      _ex('pp_abs_ex4', 'Core | Crunch', 3, '30s', 15,
        'Tumbado con rodillas flexionadas, sube solo la parte alta de la espalda contrayendo el abdomen, sin tirar del cuello con las manos. Baja controlado sin apoyar de golpe.'),
      _ex('pp_abs_ex5', 'Core | Deadbugs', 3, '30s', 15,
        'Tumbado con brazos y piernas en el aire a 90º, extiende brazo y pierna opuestos hacia el suelo sin que la lumbar se despegue. Vuelve al centro y alterna de lado.'),
      _ex('pp_abs_ex6', 'Core | Knee to toe taps', 3, '30s', 15,
        'Tumbado con piernas elevadas, lleva alternando la mano hacia la punta del pie contrario elevando el tronco. Mantén la zona lumbar en contacto con el suelo entre repeticiones.'),
      _ex('pp_abs_ex7', 'Core | Jumping jacks plank', 3, '30s', 15,
        'En plancha alta, abre y cierra las piernas a modo de salto manteniendo la cadera estable y sin subirla. El core debe permanecer apretado en todo momento.'),
      _ex('pp_abs_ex8', 'Core | Plancha con manos distanciadas', 3, '30s', 15,
        'En plancha alta con las manos más separadas que los hombros, mantén el cuerpo en línea recta apretando abdomen y glúteos. Evita que la cadera se hunda.'),
      _ex('pp_abs_ex9', 'Estiramiento | Rodilla al pecho', 1, '12', 0,
        'Tumbada boca arriba, abraza una rodilla y llévala hacia el pecho manteniendo la otra pierna estirada o apoyada en el suelo.'),
    ]
  },

  pp_abs_enfaz: {
    id: 'pp_abs_enfaz', name: "Abs Express 15''", category: 'POR PARTES', type: 'strength',
    description: 'Los 4 movimientos con más evidencia para el abdomen',
    muscleGroups: ['Core'],
    exercises: [
      _ex('pp_abse_ex1', 'Crunch en polea alta', 3, '12-15', 60,
        'Coloca la polea perpendicular a tu columna. Al subir inhala y deja que la carga estire el abdomen desde extensión controlada; al bajar enrolla la columna en forma de C exhalando, sin mover la cadera hacia atrás.'),
      _ex('pp_abse_ex2', 'Elevación de piernas con retroversión pélvica', 3, '10-12', 60,
        'Olvídate de subir y bajar las piernas desde la cadera: haz una retroversión pélvica consciente, curvando la espalda en C y despegando el sacro del suelo. Así aíslas el abdomen en vez de los flexores de cadera.'),
      _ex('pp_abse_ex3', 'Rollout con rueda abdominal', 3, '8-10', 60,
        'Mantén una ligera flexión de columna y la pelvis bloqueada durante todo el recorrido. Inicia el retorno enroscando el abdomen, no empujando la cadera hacia atrás. Si te falta fuerza, apóyate en rodillas o usa una pared como tope.'),
      _ex('pp_abse_ex4', 'Hollowing (vacío abdominal)', 3, '5-10', 45,
        'Mete el ombligo hacia la columna y sostén la tensión. Progresión: 3x5 reps de 5s → 8 reps de 10s → 10 reps de 15s. Entrena el transverso, tu "faja" profunda que estabiliza la pelvis y protege la zona lumbar.'),
    ]
  },

  pp_glute_burner: {
    id: 'pp_glute_burner', name: 'Glute Burner', category: 'POR PARTES', type: 'strength',
    description: 'Pirámide ascendente — sin descanso',
    muscleGroups: ['Glúteos', 'Piernas'],
    exercises: [
      _ex('pp_gb_ex1', 'Clamshells', 3, '10/20/30', 0, 'Pirámide ascendente'),
      _ex('pp_gb_ex2', 'Sentadilla sin peso', 3, '10/20/30', 0, 'Pirámide ascendente'),
      _ex('pp_gb_ex3', 'Hip thrust unilateral con resistencia', 3, '10/20/30 por lado', 0, 'Pirámide ascendente'),
    ]
  },

  pp_gluteo_top: {
    id: 'pp_gluteo_top', name: 'Glúteo Top', category: 'POR PARTES', type: 'strength',
    description: 'Explosive Booty Day',
    muscleGroups: ['Glúteos', 'Piernas'],
    exercises: [
      _ex('pp_gt_ex1',  'Movilidad | Rotación interna cadera 90-90', 2, '8/lado', 15,
        'Sentado con ambas piernas flexionadas a 90 grados hacia el mismo lado, rota las rodillas hacia el lado contrario manteniendo la espalda recta.'),
      _ex('pp_gt_ex2',  'Movilidad | Hip CAR', 2, '10', 15,
        'Apoyado en una pared, dibuja el círculo más amplio posible con la pierna manteniendo la cadera estable, sin mover el tronco.'),
      _ex('pp_gt_ex3',  'Movilidad | Flexión de tobillo en sedestación', 1, '6/lado', 15,
        'Sentado, desliza el pie hacia atrás flexionando el tobillo manteniendo el talón fijo en el suelo.'),
      _ex('pp_gt_ex4',  'Movilidad | Patada de glúteo de lado a lado', 1, '8/lado', 15,
        'Boca abajo con las rodillas flexionadas, abre las piernas hacia los lados como una patada, manteniendo la pelvis fija en el suelo.'),
      _ex('pp_gt_ex5',  'Sentadilla barra alta (aproximación)', 3, '8/6/4', 180, 'Pirámide descendente'),
      _ex('pp_gt_ex6',  'Sentadilla barra alta', 2, '4-8/10-12', 90, 'Parada 1s abajo'),
      _ex('pp_gt_ex7',  'Hip Thrust', 3, '8-10/12-15/AMRAP', 0, 'Última al fallo'),
      _ex('pp_gt_ex8',  'Sentadilla búlgara en multipower', 3, '6-8/10-12', 45, 'Parada 2s abajo'),
      _ex('pp_gt_ex9',  'Hiperextensión con disco', 2, '10-15/15-17', 0,
        'Igual que la hiperextensión pero sujetando un disco contra el pecho: baja el tronco controlado y sube hasta alinear el cuerpo sin arquear en exceso la zona lumbar.'),
      _ex('pp_gt_ex10', 'Curl de femoral', 2, '10-12/12-15', 0, '2s excéntrica — última al fallo'),
      _ex('pp_gt_ex11', 'Abducción en polea', 3, '8-10/12-15/Máx', 0, '2s isométrica'),
      _ex('pp_gt_ex12', 'Cardio LISS', 1, '15 min', 0,
        'Mantén una actividad cardiovascular continua a intensidad baja-moderada durante el tiempo indicado. La respiración debe permitirte hablar sin ahogarte.'),
    ]
  },

  pp_gluteos_casa: {
    id: 'pp_gluteos_casa', name: 'Glúteos en Casa', category: 'POR PARTES', type: 'strength',
    description: 'Always is glutes time',
    muscleGroups: ['Glúteos', 'Piernas'],
    exercises: [
      _ex('pp_gc_ex1',  'Movilidad | Bisagra de cadera', 2, '10', 0,
        'Con las rodillas ligeramente flexionadas, empuja la cadera hacia atrás manteniendo la espalda recta hasta sentir el estiramiento en los isquiotibiales.'),
      _ex('pp_gc_ex2',  'Movilidad | Bridge march', 2, '10', 0,
        'En puente de glúteo, mantén la cadera elevada y estable mientras alternas subiendo una rodilla hacia el pecho sin que la cadera caiga.'),
      _ex('pp_gc_ex3',  'Movilidad | Rotación interna cadera 90-90', 2, '10', 0,
        'Sentado con ambas piernas flexionadas a 90 grados hacia el mismo lado, rota las rodillas hacia el lado contrario manteniendo la espalda recta.'),
      _ex('pp_gc_ex4',  'Peso muerto + sentadilla con kettlebell', 3, '6-8/10-12', 90,
        'Encadena un peso muerto con espalda neutra a una sentadilla goblet sujetando la kettlebell pegada al pecho, sin perder la tensión del core entre ambos.'),
      _ex('pp_gc_ex5',  'Hip thrust con mancuerna', 3, '10-15', 60,
        'Con una mancuerna apoyada sobre la cadera con las manos, empuja con los talones extendiendo la cadera por completo y aprieta el glúteo arriba.'),
      _ex('pp_gc_ex6',  'Sentadilla búlgara con peso', 3, '8-10/12-15', 30,
        'Pie trasero apoyado en un banco, sujeta el peso junto al cuerpo y baja con la pierna delantera hasta casi paralelo, sin dejar que la rodilla colapse hacia dentro.'),
      _ex('pp_gc_ex7',  'Abducción de cadera con resistencia sentada', 3, '15-20', 0,
        'Sentado con la goma rodeando ambas rodillas, empuja las piernas hacia afuera contra la resistencia. Mantén la espalda apoyada y pies fijos en el suelo.'),
      _ex('pp_gc_ex8',  'Curtsy lunges con peso', 3, '10-15', 0,
        'Con peso sujeto, cruza una pierna por detrás en diagonal flexionando ambas rodillas. Mantén el torso erguido y la rodilla delantera alineada con el pie.'),
      _ex('pp_gc_ex9',  'Clamshell con gomas', 2, '20/30', 0,
        'De lado con la goma sobre las rodillas y pies juntos, abre la rodilla superior contra la resistencia sin rotar la cadera hacia atrás. Controla también el cierre.'),
      _ex('pp_gc_ex10', 'Vuelta a la calma | Trote suave', 1, '5 min', 0,
        'Mantén un trote muy ligero y cómodo, con pasos cortos y respiración controlada, para ir bajando la intensidad de forma progresiva.'),
      _ex('pp_gc_ex11', 'Estiramiento | Glúteo medio', 1, '10', 0,
        'Tumbada boca arriba, cruza un tobillo sobre la rodilla contraria y tira de esa pierna hacia el pecho hasta sentir tensión en el glúteo.'),
      _ex('pp_gc_ex12', 'Estiramiento | Piramidal', 1, '10', 0,
        'Tumbada boca arriba, cruza un tobillo sobre la rodilla contraria y tira de esa pierna hacia el pecho hasta sentir tensión profunda en el glúteo.'),
    ]
  },

  pp_gluteos_power: {
    id: 'pp_gluteos_power', name: 'Glúteos Power', category: 'POR PARTES', type: 'strength',
    description: 'Día de glúteo, día de misa',
    muscleGroups: ['Glúteos', 'Piernas'],
    exercises: [
      _ex('pp_gp_ex1', 'Abducción de cadera en máquina', 2, '10', 90,
        'Espalda pegada al respaldo, separa las rodillas contra la resistencia de forma controlada. No uses impulso ni dejes caer el peso al volver.'),
      _ex('pp_gp_ex2', 'Peso muerto rumano (aproximación)', 3, '8/6/4', 240, 'Pirámide descendente'),
      _ex('pp_gp_ex3', 'Peso muerto rumano', 2, '4-6/8-10', 60,
        'Con rodillas semiflexionadas, baja la barra pegada a las piernas empujando la cadera hacia atrás, sintiendo el estiramiento en el femoral, y sube apretando glúteos.'),
      _ex('pp_gp_ex4', 'Sentadilla búlgara con mancuerna', 3, '6-8/10-15', 60,
        'Pie trasero apoyado en un banco, sujeta la mancuerna junto al cuerpo y baja con la pierna delantera hasta casi paralelo; mantén el torso ligeramente inclinado adelante.'),
      _ex('pp_gp_ex5', 'Hip Thrust 1/2 ROM', 2, '8-12', 0,
        'Realiza solo la mitad superior del recorrido del hip thrust, desde la posición media hasta la extensión completa, apretando fuerte el glúteo arriba.'),
      _ex('pp_gp_ex6', 'Prensa unilateral', 2, '10-12', 60,
        'Apoya un solo pie en la plataforma, empuja extendiendo la pierna sin bloquear la rodilla y controla la bajada sin que la rodilla se desvíe hacia dentro.'),
      _ex('pp_gp_ex7', 'Curl de femoral', 2, '12-15', 0, 'Al fallo'),
      _ex('pp_gp_ex8', 'Patada de glúteo en polea', 2, '12-15', 0, 'Al fallo'),
      _ex('pp_gp_ex9', 'Cardio LISS', 1, '15 min', 0, '100-120 ppm'),
    ]
  },

  pp_gluteos_piernas: {
    id: 'pp_gluteos_piernas', name: 'Glúteos y Piernas Express Casa', category: 'POR PARTES', type: 'strength',
    description: 'Solo 30 min de tu día',
    muscleGroups: ['Glúteos', 'Piernas'],
    exercises: [
      _ex('pp_gpi_ex1', 'Movilidad | Bisagra de cadera', 1, '8', 15,
        'Con las rodillas ligeramente flexionadas, empuja la cadera hacia atrás manteniendo la espalda recta hasta sentir el estiramiento en los isquiotibiales.'),
      _ex('pp_gpi_ex2', 'Movilidad | Deep squat prayer opener', 1, '10 (5/lado)', 15,
        'En sentadilla profunda, junta las manos delante del pecho y empuja los codos contra las rodillas para abrir la cadera hacia fuera.'),
      _ex('pp_gpi_ex3', 'Abducción de cadera con resistencia sentada', 3, '30s', 10,
        'Sentado con la goma rodeando ambas rodillas, empuja las piernas hacia afuera contra la resistencia. Mantén la espalda apoyada y pies fijos en el suelo.'),
      _ex('pp_gpi_ex4', 'Sentadilla isométrica', 3, '30s', 10,
        'Baja en sentadilla hasta el ángulo indicado y mantén la posición estática sin moverte, con el peso repartido en todo el pie y la espalda recta.'),
      _ex('pp_gpi_ex5', 'Peso muerto + sentadilla con kettlebell', 3, '30s', 10,
        'Encadena un peso muerto con espalda neutra a una sentadilla goblet sujetando la kettlebell pegada al pecho, sin perder la tensión del core entre ambos.'),
      _ex('pp_gpi_ex6', 'HIIT | Lunge drop', 3, '30s', 10,
        'Desde de pie, deja caer una pierna atrás hasta zancada baja tocando casi la rodilla en el suelo y vuelve a subir rápido a la posición inicial.'),
      _ex('pp_gpi_ex7', 'Hip thrust con resistencia', 3, '30s', 10,
        'Con una goma rodeando las rodillas, empuja con los talones extendiendo la cadera por completo mientras presionas las rodillas hacia fuera contra la goma.'),
      _ex('pp_gpi_ex8', 'Vuelta a la calma | Trote suave', 1, '2-3 min', 0,
        'Mantén un trote muy ligero y cómodo, con pasos cortos y respiración controlada, para ir bajando la intensidad de forma progresiva.'),
      _ex('pp_gpi_ex9', 'Estiramiento | Piramidal', 1, '5', 10,
        'Tumbada boca arriba, cruza un tobillo sobre la rodilla contraria y tira de esa pierna hacia el pecho hasta sentir tensión profunda en el glúteo.'),
    ]
  },

  pp_hombros_gym: {
    id: 'pp_hombros_gym', name: 'Hombros en Gym', category: 'POR PARTES', type: 'strength',
    description: 'Día de hombros',
    muscleGroups: ['Hombros'],
    exercises: [
      _ex('pp_hg_ex1',  'Movilidad | Cat camel', 2, '10', 15,
        'A cuatro patas, alterna arqueando la espalda hacia arriba (gato) y hundiéndola hacia abajo (camello) de forma lenta y controlada.'),
      _ex('pp_hg_ex2',  'Movilidad | Prone snow angels', 2, '10', 15,
        'Boca abajo, desliza los brazos desde los costados hacia arriba de la cabeza como si hicieras un ángel de nieve, manteniendo el pecho en el suelo.'),
      _ex('pp_hg_ex3',  'Movilidad | Shoulder CAR', 2, '10', 15,
        'De pie o sentado, dibuja el círculo más amplio posible con el brazo controlando cada fase del movimiento sin compensar con el tronco.'),
      _ex('pp_hg_ex4',  'Movilidad | Kettlebell halos', 1, '12', 15,
        'Sujeta la kettlebell cerca de la cabeza y traza un círculo alrededor de ella manteniendo el tronco estable y el abdomen firme.'),
      _ex('pp_hg_ex5',  'Press militar con barra (aproximación)', 2, '3', 180,
        'Con carga ligera, practica el patrón: barra desde los hombros, empuje vertical y core apretado para no arquear la espalda.'),
      _ex('pp_hg_ex6',  'Press militar con barra', 2, '4-6/8-10', 120,
        'Desde la altura de los hombros, empuja la barra en línea recta hacia arriba pasando cerca de la cara, sin arquear la zona lumbar.'),
      _ex('pp_hg_ex7',  'Elevaciones laterales con apoyo en banco', 3, '8-10/12-15/12-15', 0, 'Dropset'),
      _ex('pp_hg_ex8',  'Facepull en polea', 3, '10-12/12-15/12-15', 60, 'Última al fallo'),
      _ex('pp_hg_ex9',  'Elevaciones frontales con mancuernas', 2, '10', 60,
        'Con una mancuerna en cada mano, elévalas al frente hasta la altura del hombro con un ligero codo flexionado, sin usar impulso lumbar.'),
      _ex('pp_hg_ex10', 'Deltoides posterior en máquina', 2, '10-15', 0, 'Última al fallo'),
      _ex('pp_hg_ex11', 'Elevaciones laterales en polea', 2, '12-15', 0, 'Última al fallo'),
      _ex('pp_hg_ex12', 'Cardio LISS', 1, '5-10 min', 0, '100-120 ppm'),
    ]
  },

  pp_sentadilla: {
    id: 'pp_sentadilla', name: 'Mejora la Sentadilla', category: 'POR PARTES', type: 'strength',
    description: 'Squat day!',
    muscleGroups: ['Cuádriceps', 'Glúteos'],
    exercises: [
      _ex('pp_st_ex1',  'Movilidad | Flexión de tobillo con peso', 2, '8/lado', 15,
        'Con una carga sobre la rodilla, flexiona el tobillo llevando la rodilla hacia delante sobre el pie sin que el talón se levante.'),
      _ex('pp_st_ex2',  'Movilidad | Frog Rolls', 2, '10', 15,
        'Boca arriba con las rodillas abiertas y plantas de los pies juntas, rueda de lado a lado manteniendo la posición de rana.'),
      _ex('pp_st_ex3',  'Movilidad | Kettlebell leg lift over', 2, '6/lado', 15,
        'Boca arriba con la kettlebell entre los pies, eleva las piernas y desplázalas de lado a lado controlando el movimiento con el abdomen.'),
      _ex('pp_st_ex4',  'Movilidad | Rotación interna cadera 90-90', 1, '10', 15,
        'Sentado con ambas piernas flexionadas a 90 grados hacia el mismo lado, rota las rodillas hacia el lado contrario manteniendo la espalda recta.'),
      _ex('pp_st_ex5',  'Movilidad | Bisagra de cadera', 2, '10', 15,
        'Con las rodillas ligeramente flexionadas, empuja la cadera hacia atrás manteniendo la espalda recta hasta sentir el estiramiento en los isquiotibiales.'),
      _ex('pp_st_ex6',  'Extensión del dedo gordo del pie', 1, '8/pie', 15,
        'Sentada con el pie apoyado, eleva solo el dedo gordo del pie manteniendo el resto de dedos relajados en el suelo, trabajando el control del pie.'),
      _ex('pp_st_ex7',  'Sentadilla barra alta (aproximación)', 3, '8/6/4', 240,
        'Con la barra apoyada sobre los trapecios, practica el patrón con poco o ningún peso: torso erguido, cadera hacia atrás y rodillas hacia fuera al bajar.'),
      _ex('pp_st_ex8',  'Sentadilla barra alta', 3, '4-6/6-8/10-12', 120,
        'Con la barra apoyada sobre los trapecios (arriba de la espalda), baja manteniendo el torso más erguido; las rodillas pueden avanzar ligeramente sobre la punta del pie.'),
      _ex('pp_st_ex9',  'Extensión de cuádriceps', 2, '10-12/12-15', 60,
        'Sentada en la máquina, extiende las rodillas hasta casi estirar del todo, controlando la vuelta sin dejar caer el peso de golpe.'),
      _ex('pp_st_ex10', 'Curtsy lunges con mancuerna', 2, '10/12 por pierna', 60,
        'Con una mancuerna sujeta, cruza una pierna por detrás en diagonal flexionando ambas rodillas. Mantén el torso erguido y la rodilla delantera alineada con el pie.'),
      _ex('pp_st_ex11', 'Curl de femoral con fitball', 2, '10-15', 60,
        'Tumbada boca arriba, talones sobre el fitball, eleva la cadera y flexiona rodillas rodando la pelota hacia los glúteos. Siente el trabajo en femorales, no en lumbares.'),
      _ex('pp_st_ex12', 'Estiramiento | Aductores (Mariposa)', 1, '12/lado', 15,
        'Sentada con plantas de los pies juntas y rodillas hacia fuera, inclina el tronco al frente con la espalda recta hasta sentir tensión suave en la ingle.'),
      _ex('pp_st_ex13', 'Estiramiento | Piramidal sentada', 1, '10/lado', 15,
        'Sentada, cruza un tobillo sobre la rodilla contraria e inclina el tronco al frente manteniendo la espalda recta hasta sentir tensión en el glúteo.'),
    ]
  },

  pp_piernas_gym: {
    id: 'pp_piernas_gym', name: 'Piernas Gym', category: 'POR PARTES', type: 'strength',
    description: 'Leg day',
    muscleGroups: ['Cuádriceps', 'Glúteos'],
    exercises: [
      _ex('pp_pg_ex1', 'HIIT | Spider lunges', 1, '10', 60,
        'Desde plancha alta, lleva una rodilla hacia el codo del mismo lado por fuera del brazo y regresa, alternando piernas con ritmo controlado.'),
      _ex('pp_pg_ex2', 'Movilidad | Flexión de tobillo con peso', 1, '30s/pierna', 0,
        'Con una carga sobre la rodilla, flexiona el tobillo llevando la rodilla hacia delante sobre el pie sin que el talón se levante.'),
      _ex('pp_pg_ex3', 'Sentadilla barra alta', 3, '8', 180,
        'Con la barra apoyada sobre los trapecios (arriba de la espalda), baja manteniendo el torso más erguido; las rodillas pueden avanzar ligeramente sobre la punta del pie.'),
      _ex('pp_pg_ex4', 'Sentadilla sin peso', 2, '20', 30,
        'Pies a la anchura de los hombros, baja empujando la cadera hacia atrás y las rodillas hacia fuera sin usar peso adicional; mantén la espalda recta.'),
      _ex('pp_pg_ex5', 'Hip Thrust', 3, '8', 120,
        'Espalda apoyada en el banco a la altura de la escápula, pies firmes cerca de la cadera; empuja con los talones extendiendo la cadera del todo y aprieta el glúteo arriba sin arquear la lumbar.'),
      _ex('pp_pg_ex6', 'Hip Thrust 1/2 ROM', 2, '20', 0,
        'Realiza solo la mitad superior del recorrido del hip thrust, desde la posición media hasta la extensión completa, apretando fuerte el glúteo arriba.'),
      _ex('pp_pg_ex7', 'Extensión de cuádriceps', 3, '10/10/Máx', 30, 'Última al fallo'),
    ]
  },

  pp_push_day: {
    id: 'pp_push_day', name: 'Push Day Gym', category: 'POR PARTES', type: 'strength',
    description: 'Pecho, hombro y tríceps',
    muscleGroups: ['Pecho', 'Hombros', 'Tríceps'],
    exercises: [
      _ex('pp_pd_ex1',  'Movilidad | Shoulder CAR', 2, '8/mano', 15,
        'De pie o sentado, dibuja el círculo más amplio posible con el brazo controlando cada fase del movimiento sin compensar con el tronco.'),
      _ex('pp_pd_ex2',  'Movilidad | Rotación de columna en cuadrupedia', 2, '8/lado', 15,
        'A cuatro patas, lleva un brazo por debajo del cuerpo rotando la columna y luego ábrelo hacia arriba siguiendo la mano con la mirada.'),
      _ex('pp_pd_ex3',  'Movilidad | Manguitos rotadores con resistencia', 2, '10/lado', 15,
        'Con el codo pegado al cuerpo y flexionado 90 grados, rota el brazo hacia fuera venciendo la resistencia de la goma, sin mover el codo.'),
      _ex('pp_pd_ex4',  'Press banca con barra', 4, '8 / 6 / 6-8 / 8-10', 240,
        'Baja la barra controlada hasta tocar el pecho a la altura de las tetillas, con los codos a unos 45 grados, y empuja hacia arriba sin despegar los glúteos del banco.'),
      _ex('pp_pd_ex5',  'Fondos de tríceps en paralelas', 3, '4-6/8-10/11-16', 60,
        'Sujeta las paralelas con los hombros ligeramente inclinados hacia delante, baja flexionando los codos hasta sentir el estiramiento en el pecho/tríceps y empuja para subir.'),
      _ex('pp_pd_ex6',  'Cruce de poleas ascendente', 3, '12-15', 60, 'Última al fallo'),
      _ex('pp_pd_ex7',  'Extensiones tríceps trasnuca polea baja', 2, '12-15/Máx', 0, '2ª serie: -20% peso'),
      _ex('pp_pd_ex8',  'Extensión de tríceps unilateral en polea', 2, '10-12/12-15', 60, 'Última al fallo'),
      _ex('pp_pd_ex9',  'Cardio LISS', 1, '15 min', 0,
        'Mantén una actividad cardiovascular continua a intensidad baja-moderada durante el tiempo indicado. La respiración debe permitirte hablar sin ahogarte.'),
      _ex('pp_pd_ex10', 'Estiramiento | Hombros', 1, '10', 15,
        'Cruza un brazo por delante del pecho y presiona suavemente con el otro brazo hasta sentir tensión en la parte trasera del hombro.'),
      _ex('pp_pd_ex11', 'Estiramiento | Tríceps', 1, '10', 15,
        'Con un brazo flexionado detrás de la cabeza, empuja suavemente el codo hacia atrás con la otra mano hasta sentir tensión en el tríceps.'),
    ]
  },

  pp_tren_superior: {
    id: 'pp_tren_superior', name: 'Tren Superior', category: 'POR PARTES', type: 'strength',
    description: '¿Lunes? ¡Entrena!',
    muscleGroups: ['Pecho', 'Espalda', 'Hombros', 'Brazos'],
    exercises: [
      _ex('pp_ts_ex1',  'Movilidad | Cat camel', 2, '10', 10,
        'A cuatro patas, alterna arqueando la espalda hacia arriba (gato) y hundiéndola hacia abajo (camello) de forma lenta y controlada.'),
      _ex('pp_ts_ex2',  'Movilidad | Prone snow angels', 2, '10', 10,
        'Boca abajo, desliza los brazos desde los costados hacia arriba de la cabeza como si hicieras un ángel de nieve, manteniendo el pecho en el suelo.'),
      _ex('pp_ts_ex3',  'Movilidad | Rotación de hombro de rodillas', 1, '6/lado', 10,
        'De rodillas con una mano apoyada, rota el brazo libre hacia arriba abriendo el pecho y sigue el movimiento con la mirada.'),
      _ex('pp_ts_ex4',  'Movilidad | Cervicales', 1, '12', 10,
        'Sentado o de pie, inclina la cabeza suavemente hacia cada lado y adelante, sin forzar, hasta notar un estiramiento leve en el cuello.'),
      _ex('pp_ts_ex5',  'Press banca inclinado con mancuernas', 3, '8/8/10', 120,
        'En el banco inclinado, baja las mancuernas a la altura de la parte alta del pecho y empuja hacia arriba sin arquear excesivamente la lumbar.'),
      _ex('pp_ts_ex6',  'Remo con barra a 90°', 2, '4-6/8-10', 120,
        'Con el tronco inclinado a 90 grados y espalda neutra, tira de la barra hacia el abdomen llevando los codos atrás, sin usar el impulso de la espalda.'),
      _ex('pp_ts_ex7',  'Press militar en máquina', 3, '10-12/10-12/12-15', 60, 'Última al fallo'),
      _ex('pp_ts_ex8',  'Australian pull-ups', 2, '7-9/Máx', 60, 'Última al fallo'),
      _ex('pp_ts_ex9',  'Remo gironda en polea', 2, '10-12/12-15', 0, 'Última al fallo'),
      _ex('pp_ts_ex10', 'Extensión de tríceps unilateral en polea', 2, '10-15', 0, 'Al fallo'),
      _ex('pp_ts_ex11', 'Curl de bíceps en banco inclinado', 2, '10-15', 0, 'Al fallo'),
      _ex('pp_ts_ex12', 'Elevaciones laterales en polea', 2, '8-10/12-15', 0, 'Última al fallo'),
      _ex('pp_ts_ex13', 'Cardio LISS', 1, '15 min', 0,
        'Mantén una actividad cardiovascular continua a intensidad baja-moderada durante el tiempo indicado. La respiración debe permitirte hablar sin ahogarte.'),
    ]
  },

  /* ══════════════ CALISTENIA ══════════════ */

  calistenia_parque: {
    id: 'calistenia_parque', name: 'Calistenia en el Parque', category: 'CALISTENIA', type: 'strength',
    description: 'Día de barras',
    muscleGroups: ['Full Body', 'Calistenia'],
    exercises: [
      _ex('cal_pq_ex1',  'Movilidad | Shoulder CAR', 2, '12/brazo', 30,
        'De pie o sentado, dibuja el círculo más amplio posible con el brazo controlando cada fase del movimiento sin compensar con el tronco.'),
      _ex('cal_pq_ex2',  'Movilidad | Cat camel', 2, '10', 30,
        'A cuatro patas, alterna arqueando la espalda hacia arriba (gato) y hundiéndola hacia abajo (camello) de forma lenta y controlada.'),
      _ex('cal_pq_ex3',  'Movilidad | Movimientos escapulares', 2, '10', 30,
        'En posición de plancha o cuadrupedia, junta y separa los omóplatos manteniendo los brazos extendidos, sin flexionar los codos.'),
      _ex('cal_pq_ex4',  "Movilidad | WGS (World's Greatest Stretch)", 1, '10', 30,
        'Desde zancada profunda, apoya la mano interior en el suelo y rota el tronco abriendo el brazo contrario hacia el techo, siguiendo con la mirada.'),
      _ex('cal_pq_ex5',  'Dominadas negativas', 3, '5s bajada', 90,
        'Sube con ayuda o salto hasta arriba de la barra y baja lo más lenta y controlada posible, resistiendo con la espalda hasta extender los brazos.'),
      _ex('cal_pq_ex6',  'Remo en TRX', 3, '12', 60,
        'Sujeta las cintas con el cuerpo inclinado hacia atrás y tira del pecho hacia las manos llevando los codos atrás, sin dejar caer la cadera.'),
      _ex('cal_pq_ex7',  'Flexiones con elevación (aproximación)', 2, '8', 90,
        'Serie de aproximación: manos sobre el apoyo elevado, cuerpo recto, bajas controlado sin llegar al fallo para preparar la técnica antes del set de trabajo.'),
      _ex('cal_pq_ex8',  'Flexiones con elevación (trabajo)', 2, '10-15', 90,
        'Manos sobre el apoyo elevado, cuerpo en línea recta, bajas el pecho hasta rozar el borde y empujas fuerte manteniendo el core firme durante toda la serie.'),
      _ex('cal_pq_ex9',  'Sentadilla con rebote (aproximación)', 1, '10', 60,
        'Practica el patrón de sentadilla con rebote sin peso o con carga ligera: baja, rebota suave en el fondo y sube con control.'),
      _ex('cal_pq_ex10', 'Sentadilla con rebote (trabajo)', 3, '15', 60,
        'Baja en sentadilla y en el punto más bajo realiza un pequeño rebote controlado antes de subir con fuerza; mantén la espalda recta en todo momento.'),
      _ex('cal_pq_ex11', 'Fondos de tríceps en banco (aproximación)', 1, '8', 60,
        'Serie de aproximación con menor rango o menos peso corporal en las piernas, controlando la bajada de los codos hacia atrás para preparar el set de trabajo.'),
      _ex('cal_pq_ex12', 'Fondos de tríceps en banco (trabajo)', 2, '10', 60,
        'Manos en el borde del banco, baja el cuerpo flexionando los codos hacia atrás hasta 90° manteniendo los hombros bajos y empuja fuerte para subir.'),
      _ex('cal_pq_ex13', 'Dominadas con gomas (aproximación)', 1, 'Máximas', 120,
        'Con la goma dando asistencia bajo el pie o rodilla, tira desde escápulas hasta pasar la barbilla la barra, controlando la bajada completa.'),
      _ex('cal_pq_ex14', 'Dominadas con gomas (trabajo)', 3, '4-8 sin fallo', 90,
        'Con menos asistencia de la goma, tira desde escápulas hasta pasar la barbilla la barra, controlando la bajada completa sin balanceo.'),
      _ex('cal_pq_ex15', 'Estiramiento | Espalda', 1, '20s', 0,
        'Sentada o de rodillas, redondea la espalda llevando los brazos al frente y el pecho hacia el suelo, dejando que la zona dorsal se estire pasivamente.'),
      _ex('cal_pq_ex16', 'Estiramiento | Piramidal sentada', 1, '20s', 0,
        'Sentada, cruza un tobillo sobre la rodilla contraria e inclina el tronco al frente manteniendo la espalda recta hasta sentir tensión en el glúteo.'),
    ]
  },

  /* ══════════════ KETTLEBELL ══════════════ */

  kettlebell_express: {
    id: 'kettlebell_express', name: 'Entrenamiento con Kettlebell', category: 'KETTLEBELL', type: 'strength',
    description: 'Sábado en casa — 3 rondas 40s / 20s',
    muscleGroups: ['Full Body', 'Kettlebell'],
    exercises: [
      _ex('kb_ex1',  'Movilidad | Kettlebell leg lift over', 2, '8/lado', 0,
        'Boca arriba con la kettlebell entre los pies, eleva las piernas y desplázalas de lado a lado controlando el movimiento con el abdomen.'),
      _ex('kb_ex2',  'Movilidad | Cervicales', 2, '8', 0,
        'Sentado o de pie, inclina la cabeza suavemente hacia cada lado y adelante, sin forzar, hasta notar un estiramiento leve en el cuello.'),
      _ex('kb_ex3',  'Movilidad | Aductores con kettlebell', 2, '8/pierna', 0,
        'En sentadilla amplia, sujeta la kettlebell cerca del pecho y balancéate de lado a lado empujando la rodilla hacia fuera para abrir la cadera.'),
      _ex('kb_ex4',  'Movilidad | Kettlebell halos', 2, '6/lado', 0,
        'Sujeta la kettlebell cerca de la cabeza y traza un círculo alrededor de ella manteniendo el tronco estable y el abdomen firme.'),
      _ex('kb_ex5',  'Rack kettlebell squat', 3, '40s', 20,
        'Sujeta la kettlebell apoyada sobre el antebrazo a la altura del pecho y baja en sentadilla manteniendo el torso erguido y las rodillas alineadas.'),
      _ex('kb_ex6',  'Gorilla row', 3, '40s (20s/mano)', 20,
        'Con dos mancuernas o discos en el suelo entre las piernas, cadera atrás y espalda recta, rema alternando brazos tirando del peso hacia la cadera.'),
      _ex('kb_ex7',  'Kettlebell swing', 1, '40s', 20,
        'Con la kettlebell entre las piernas, impulsa desde la cadera hacia atrás y adelante, sin usar los brazos para levantarla ni flexionar mucho las rodillas.'),
      _ex('kb_ex8',  'Kettlebell clean and press', 3, '40s', 20,
        'Sube la kettlebell desde el suelo hasta el hombro con un movimiento fluido de cadera y luego empújala por encima de la cabeza sin arquear la espalda.'),
      _ex('kb_ex9',  'Core | Pass through con kettlebell', 3, '40s', 20,
        'Sentado con piernas elevadas y flexionadas, pasa la kettlebell por debajo de las piernas de mano a mano manteniendo el equilibrio con el abdomen. No dejes caer los pies al suelo.'),
      _ex('kb_ex10', 'Vuelta a la calma | Trote suave', 1, '3-5 min', 0,
        'Mantén un trote muy ligero y cómodo, con pasos cortos y respiración controlada, para ir bajando la intensidad de forma progresiva.'),
      _ex('kb_ex11', 'Estiramiento | Cadera (Frog)', 2, '8', 0,
        'A cuatro patas, separa las rodillas hacia los lados y lleva la cadera hacia atrás manteniendo los tobillos flexionados, hasta sentir tensión en la ingle.'),
      _ex('kb_ex12', 'Estiramiento | Piramidal', 2, '8', 0,
        'Tumbada boca arriba, cruza un tobillo sobre la rodilla contraria y tira de esa pierna hacia el pecho hasta sentir tensión profunda en el glúteo.'),
      _ex('kb_ex13', 'Estiramientos circulares', 2, '8', 0,
        'Realiza círculos amplios y controlados con la articulación indicada, aumentando poco a poco el rango sin forzar ni sentir dolor.'),
    ]
  },

  /* ══════════════ MOVILIDAD ══════════════ */

  mov_cadera: {
    id: 'mov_cadera', name: 'Dolor de Cadera', category: 'MOVILIDAD', type: 'strength',
    description: 'Reduce tu dolor de cadera',
    muscleGroups: ['Movilidad', 'Cadera'],
    exercises: [
      _ex('mov_cad_ex1', 'Estiramientos | Sitting reach', 2, '10/lado', 30,
        'Sentada con piernas extendidas al frente, inclina el tronco hacia delante buscando los pies con las manos, manteniendo la espalda lo más recta posible.'),
      _ex('mov_cad_ex2', 'Movilidad | Rotación interna cadera 90-90', 3, '10/lado', 30,
        'Sentado con ambas piernas flexionadas a 90 grados hacia el mismo lado, rota las rodillas hacia el lado contrario manteniendo la espalda recta.'),
      _ex('mov_cad_ex3', 'Movilidad | Frog Rolls', 3, '10', 30,
        'Boca arriba con las rodillas abiertas y plantas de los pies juntas, rueda de lado a lado manteniendo la posición de rana.'),
      _ex('mov_cad_ex4', "Movilidad | WGS (World's Greatest Stretch)", 3, '10/lado', 30,
        'Desde zancada profunda, apoya la mano interior en el suelo y rota el tronco abriendo el brazo contrario hacia el techo, siguiendo con la mirada.'),
      _ex('mov_cad_ex5', 'Estiramiento | Piramidal sentada', 2, '8/lado', 30,
        'Sentada, cruza un tobillo sobre la rodilla contraria e inclina el tronco al frente manteniendo la espalda recta hasta sentir tensión en el glúteo.'),
      _ex('mov_cad_ex6', 'Estiramiento | Media mariposa en torsión', 2, '8/lado', 30,
        'Sentada con una pierna flexionada hacia dentro y la otra extendida, gira el tronco hacia la pierna flexionada apoyando la mano contraria en la rodilla.'),
    ]
  },

  mov_vacaciones: {
    id: 'mov_vacaciones', name: 'Movilidad de Vacaciones', category: 'MOVILIDAD', type: 'strength',
    description: 'No te oxides de vacaciones',
    muscleGroups: ['Movilidad'],
    exercises: [
      _ex('mov_vac_ex1', 'Movilidad | Rotación de columna en T', 2, '8/lado', 15,
        'Tumbado de lado con rodillas flexionadas, abre el brazo de arriba rotando el pecho hacia atrás formando una T, sin mover la cadera.'),
      _ex('mov_vac_ex2', 'Estiramiento | Espalda en cajón', 1, '12', 15,
        'Con los pies apoyados en un cajón o banco y manos en el suelo delante, deja caer el pecho entre los brazos para estirar la espalda con más rango.'),
      _ex('mov_vac_ex3', 'Estiramiento | Piramidal sentada', 2, '10/lado', 15,
        'Sentada, cruza un tobillo sobre la rodilla contraria e inclina el tronco al frente manteniendo la espalda recta hasta sentir tensión en el glúteo.'),
      _ex('mov_vac_ex4', 'Movilidad | Leg Rockback', 1, '8/lado', 15,
        'Desde cuadrupedia, siéntate hacia atrás sobre los talones manteniendo las manos fijas para movilizar cadera y hombros.'),
      _ex('mov_vac_ex5', 'Estiramientos | Unilateral sitting reach', 1, '12/lado + 5s', 15,
        'Sentada con una pierna extendida y la otra flexionada hacia dentro, inclina el tronco hacia la pierna extendida buscando el pie con las manos.'),
    ]
  },

  mov_oficinistas: {
    id: 'mov_oficinistas', name: 'Movilidad para Oficinistas', category: 'MOVILIDAD', type: 'strength',
    description: 'Adiós al dolor de espalda y cuello',
    muscleGroups: ['Movilidad', 'Espalda'],
    exercises: [
      _ex('mov_of_ex1', 'Movilidad | Cat camel', 3, '10', 10,
        'A cuatro patas, alterna arqueando la espalda hacia arriba (gato) y hundiéndola hacia abajo (camello) de forma lenta y controlada.'),
      _ex('mov_of_ex2', 'Estiramiento | Espalda en cajón', 3, '8', 10,
        'Con los pies apoyados en un cajón o banco y manos en el suelo delante, deja caer el pecho entre los brazos para estirar la espalda con más rango.'),
      _ex('mov_of_ex3', 'Movilidad | Cervicales', 3, '12', 10,
        'Sentado o de pie, inclina la cabeza suavemente hacia cada lado y adelante, sin forzar, hasta notar un estiramiento leve en el cuello.'),
      _ex('mov_of_ex4', 'Movilidad | Rotación de columna en T', 3, '8/lado', 10,
        'Tumbado de lado con rodillas flexionadas, abre el brazo de arriba rotando el pecho hacia atrás formando una T, sin mover la cadera.'),
      _ex('mov_of_ex5', 'Movilidad | Movimientos escapulares', 3, '12', 10,
        'En posición de plancha o cuadrupedia, junta y separa los omóplatos manteniendo los brazos extendidos, sin flexionar los codos.'),
    ]
  },

  mov_casa_1: {
    id: 'mov_casa_1', name: 'Movilidad y Estiramientos en Casa 1', category: 'MOVILIDAD', type: 'strength',
    description: 'Día de relax en casa',
    muscleGroups: ['Movilidad', 'Full Body'],
    exercises: [
      _ex('mov_c1_ex1',  'Foam roller | Glúteo medio', 2, '15', 30,
        'Sentado apoyando un lateral del glúteo sobre el rodillo con la pierna cruzada, rueda despacio buscando la zona lateral de la cadera.'),
      _ex('mov_c1_ex2',  'Foam roller | Cuádriceps', 2, '15', 30,
        'Boca abajo apoyando los antebrazos, coloca el rodillo bajo los muslos y desplázate desde la cadera hasta la rodilla presionando el peso del cuerpo.'),
      _ex('mov_c1_ex3',  'Foam roller | Femoral', 1, '15', 30,
        'Sentado con el rodillo bajo la parte posterior del muslo, apoya las manos detrás y desplázate desde la rodilla hasta el glúteo con presión controlada.'),
      _ex('mov_c1_ex4',  "Movilidad | WGS (World's Greatest Stretch)", 3, '10', 30,
        'Desde zancada profunda, apoya la mano interior en el suelo y rota el tronco abriendo el brazo contrario hacia el techo, siguiendo con la mirada.'),
      _ex('mov_c1_ex5',  'Movilidad | Cervicales', 3, '10', 30,
        'Sentado o de pie, inclina la cabeza suavemente hacia cada lado y adelante, sin forzar, hasta notar un estiramiento leve en el cuello.'),
      _ex('mov_c1_ex6',  'Movilidad | Cat camel', 3, '10', 30,
        'A cuatro patas, alterna arqueando la espalda hacia arriba (gato) y hundiéndola hacia abajo (camello) de forma lenta y controlada.'),
      _ex('mov_c1_ex7',  'Movilidad | Flexión de tobillo de rodillas', 3, '10', 30,
        'De rodillas, empuja la cadera hacia atrás sentándote sobre el talón mientras el pie se mantiene plano en el suelo.'),
      _ex('mov_c1_ex8',  'Movilidad | Rotación de columna en T', 3, '10 (5/lado)', 30,
        'Tumbado de lado con rodillas flexionadas, abre el brazo de arriba rotando el pecho hacia atrás formando una T, sin mover la cadera.'),
      _ex('mov_c1_ex9',  'Movilidad | Standing reach down fwd-back', 3, '10', 30,
        'De pie, inclínate llevando las manos hacia el suelo por delante y luego arquéate suavemente hacia atrás, con control.'),
      _ex('mov_c1_ex10', 'Estiramientos circulares', 2, '15', 30,
        'Realiza círculos amplios y controlados con la articulación indicada, aumentando poco a poco el rango sin forzar ni sentir dolor.'),
      _ex('mov_c1_ex11', 'Estiramiento | Rodilla al pecho', 2, '12 (6/lado)', 30,
        'Tumbada boca arriba, abraza una rodilla y llévala hacia el pecho manteniendo la otra pierna estirada o apoyada en el suelo.'),
      _ex('mov_c1_ex12', 'Estiramientos | Unilateral sitting reach', 2, '6/lado', 30,
        'Sentada con una pierna extendida y la otra flexionada hacia dentro, inclina el tronco hacia la pierna extendida buscando el pie con las manos.'),
    ]
  },

  mov_casa_2: {
    id: 'mov_casa_2', name: 'Movilidad y Estiramientos en Casa 2', category: 'MOVILIDAD', type: 'strength',
    description: 'Día de relax II',
    muscleGroups: ['Movilidad', 'Full Body'],
    exercises: [
      _ex('mov_c2_ex1',  'Foam roller | Aductor', 2, '8/lado', 30,
        'Tumbado boca abajo con una pierna abierta hacia el lado, coloca el rodillo bajo la ingle/aductor y desplázate despacio buscando puntos de tensión.'),
      _ex('mov_c2_ex2',  'Foam roller | Gemelos', 2, '8/lado', 30,
        'Sentado con el rodillo bajo la pantorrilla y el peso apoyado en las manos, rueda desde el tobillo hasta la rodilla, girando la pierna para cubrir todo el gemelo.'),
      _ex('mov_c2_ex3',  'Foam roller | Glúteo medio', 2, '10', 30,
        'Sentado apoyando un lateral del glúteo sobre el rodillo con la pierna cruzada, rueda despacio buscando la zona lateral de la cadera.'),
      _ex('mov_c2_ex4',  'Movilidad | Prone snow angels', 2, '10', 30,
        'Boca abajo, desliza los brazos desde los costados hacia arriba de la cabeza como si hicieras un ángel de nieve, manteniendo el pecho en el suelo.'),
      _ex('mov_c2_ex5',  'Movilidad | Hip CAR', 2, '10', 30,
        'Apoyado en una pared, dibuja el círculo más amplio posible con la pierna manteniendo la cadera estable, sin mover el tronco.'),
      _ex('mov_c2_ex6',  'Movilidad | Shoulder CAR', 2, '10', 30,
        'De pie o sentado, dibuja el círculo más amplio posible con el brazo controlando cada fase del movimiento sin compensar con el tronco.'),
      _ex('mov_c2_ex7',  'Movilidad | Runners lunge with reach', 2, '10', 30,
        'En zancada profunda, además de empujar la cadera hacia el suelo, eleva el brazo del lado de la pierna adelantada rotando el tronco hacia arriba.'),
      _ex('mov_c2_ex8',  'Estiramientos | Cadera (Pigeon)', 1, '12', 15,
        'Sentada con una pierna flexionada al frente y la otra estirada atrás, inclina el tronco hacia delante manteniendo la cadera cuadrada, sin forzar la rodilla.'),
      _ex('mov_c2_ex9',  'Estiramiento | Espalda en cajón', 1, '12', 15,
        'Con los pies apoyados en un cajón o banco y manos en el suelo delante, deja caer el pecho entre los brazos para estirar la espalda con más rango.'),
      _ex('mov_c2_ex10', 'Estiramientos circulares', 1, '12', 15,
        'Realiza círculos amplios y controlados con la articulación indicada, aumentando poco a poco el rango sin forzar ni sentir dolor.'),
      _ex('mov_c2_ex11', 'Estiramiento | Split unilateral', 1, '6/lado', 15,
        'En posición de zancada baja con la pierna trasera estirada, hunde la cadera hacia delante y abajo para estirar cadera y cuádriceps de la pierna de atrás.'),
      _ex('mov_c2_ex12', 'Estiramiento | Upward dog', 1, '10', 15,
        'Desde boca abajo, empuja con los brazos elevando el pecho y estirando los codos, manteniendo la cadera baja y los hombros alejados de las orejas.'),
    ]
  },

  mov_espalda: {
    id: 'mov_espalda', name: 'Reduce tu Dolor de Espalda', category: 'MOVILIDAD', type: 'strength',
    description: 'Movilidad y estiramientos para la espalda',
    muscleGroups: ['Movilidad', 'Espalda'],
    exercises: [
      _ex('mov_esp_ex1', 'Estiramiento | Espalda', 2, '10', 15,
        'Sentada o de rodillas, redondea la espalda llevando los brazos al frente y el pecho hacia el suelo, dejando que la zona dorsal se estire pasivamente.'),
      _ex('mov_esp_ex2', 'Movilidad | Cervicales', 2, '8', 15,
        'Sentado o de pie, inclina la cabeza suavemente hacia cada lado y adelante, sin forzar, hasta notar un estiramiento leve en el cuello.'),
      _ex('mov_esp_ex3', 'Estiramiento | Rodilla al pecho', 2, '10/pierna', 15,
        'Tumbada boca arriba, abraza una rodilla y llévala hacia el pecho manteniendo la otra pierna estirada o apoyada en el suelo.'),
      _ex('mov_esp_ex4', "Movilidad | WGS (World's Greatest Stretch)", 2, '10/lado', 15,
        'Desde zancada profunda, apoya la mano interior en el suelo y rota el tronco abriendo el brazo contrario hacia el techo, siguiendo con la mirada.'),
      _ex('mov_esp_ex5', 'Estiramientos circulares', 2, '6/lado', 15,
        'Realiza círculos amplios y controlados con la articulación indicada, aumentando poco a poco el rango sin forzar ni sentir dolor.'),
    ]
  },

  /* ══════════════ ESTIRAMIENTOS ══════════════ */

  estiramientos: {
    id: 'estiramientos', name: 'Estiramientos', category: 'ESTIRAMIENTOS', type: 'strength',
    description: 'Mejora tu salud estando de vacaciones',
    muscleGroups: ['Estiramientos', 'Movilidad'],
    exercises: [
      _ex('est_ex1', 'Movilidad | Bisagra de cadera', 3, '10', 15,
        'Con las rodillas ligeramente flexionadas, empuja la cadera hacia atrás manteniendo la espalda recta hasta sentir el estiramiento en los isquiotibiales.'),
      _ex('est_ex2', 'Movilidad | Flexión de tobillo de rodillas', 3, '10/pierna', 15,
        'De rodillas, empuja la cadera hacia atrás sentándote sobre el talón mientras el pie se mantiene plano en el suelo.'),
      _ex('est_ex3', 'Estiramiento | Hombros con rotación', 3, '12/mano', 15,
        'Cruza un brazo por delante del pecho y añade una ligera rotación de tronco hacia el lado contrario para ampliar el estiramiento del hombro.'),
      _ex('est_ex4', 'Movilidad | Fire Hydrants', 3, '10/pierna', 15,
        'A cuatro patas, eleva una rodilla hacia el lado manteniendo el ángulo de 90 grados, sin rotar la cadera ni arquear la espalda.'),
      _ex('est_ex5', 'Movilidad | Bridge march', 3, '12/pierna', 15,
        'En puente de glúteo, mantén la cadera elevada y estable mientras alternas subiendo una rodilla hacia el pecho sin que la cadera caiga.'),
      _ex('est_ex6', 'Movilidad | Scorpions', 3, '7/pierna', 15,
        'Boca abajo, lleva un pie hacia la mano contraria rotando la cadera, manteniendo el pecho pegado al suelo.'),
    ]
  },
};

function getExpressByCategory() {
  const grouped = {};
  EXPRESS_CATEGORIES.forEach(cat => { grouped[cat.id] = []; });
  Object.values(EXPRESS_WORKOUTS).forEach(w => {
    if (grouped[w.category]) grouped[w.category].push(w);
  });
  return grouped;
}
