/* ============================================
   IZA WORKOUT — Planes adicionales
   Carrera 5KM · Pérdida de Grasa · Quema Grasa Complemento
   Se fusionan en WORKOUT_PLANS al cargar.
   ============================================ */

/* ══════════════ CARRERA 5KM (3 semanas) ══════════════ */
WORKOUT_PLANS.carrera_5km = {
  id: 'carrera_5km',
  name: 'Carrera 5KM',
  planType: 'phased',
  weeks: 3,
  description: 'Plan de 3 semanas para correr 5km (método Ca-Co + trabajo preventivo)',
  trainingDays: [1, 3, 4, 5, 6],
  dayMeta: {
    1: { name: 'Ca-Co + Movilidad',            type: 'running',  muscleGroups: ['Cardio', 'Movilidad'] },
    3: { name: 'Ca-Co + Movilidad',            type: 'running',  muscleGroups: ['Cardio', 'Movilidad'] },
    4: { name: 'Prevención de lesiones',       type: 'strength', muscleGroups: ['Gemelos', 'Tobillo', 'Cadera'] },
    5: { name: 'Ca-Co + Movilidad',            type: 'running',  muscleGroups: ['Cardio', 'Movilidad'] },
    6: { name: 'Prevención de lesiones',       type: 'strength', muscleGroups: ['Gemelos', 'Cuádriceps', 'Piernas'] }
  },
  weeklySchedule: [
    // S1
    {
      1: [
        _ex('c5k_m_balanceo', 'Movilidad | Balanceo de piernas', 1, '10/pierna', 0),
        _ex('c5k_m_flex_sed',  'Movilidad | Flexión de tobillo sedestación', 1, '10/pierna', 0),
        _ex('c5k_m_squat_rod', 'Sentadilla + rodilla al pecho', 1, '5/lado', 0),
        _ex('c5k_caco',        'Correr (Ca-Co)', 3, '1 min correr + 9 min andar', 0, '30 min total. Intensidad conversacional.'),
      ],
      3: [
        _ex('c5k_m_hip_car',  'Movilidad | Hip CAR', 1, '10/pierna', 0),
        _ex('c5k_m_flex_bip', 'Movilidad | Flexión de tobillo bipedestación', 1, '8/lado', 0),
        _ex('c5k_m_balanceo', 'Movilidad | Balanceo de piernas', 1, '10/pierna', 0),
        _ex('c5k_caco',       'Correr (Ca-Co)', 4, '1 min correr + 7 min andar', 0, '32 min total'),
      ],
      4: [
        _ex('c5k_m_rockback', 'Movilidad | Leg Rockback', 2, '9/lado', 90),
        _ex('c5k_m_flex_sed', 'Movilidad | Flexión de tobillo sedestación', 2, '9/lado', 90),
        _ex('c5k_gemelo_mc',  'Gemelo con mancuernas sentada', 2, '9', 90),
      ],
      5: [
        _ex('c5k_m_rlunge', 'Movilidad | Runners lunge', 1, '8/lado', 0),
        _ex('c5k_caco',     'Correr (Ca-Co)', 5, '1 min correr + 5 min andar', 0, '30 min total'),
      ],
      6: [
        _ex('c5k_m_rockback', 'Movilidad | Leg Rockback', 2, '9/lado', 90),
        _ex('c5k_ext_dedo',   'Extensión del dedo gordo', 2, '9/lado', 90),
        _ex('c5k_gemelo_mc',  'Gemelo con mancuernas sentada', 2, '9/lado', 90),
        _ex('c5k_fr_cuad',    'Foam roller | Cuádriceps', 2, '9', 90),
        _ex('c5k_step_up',    'Step up con mancuerna', 2, '9/pierna', 90),
        _ex('c5k_pistol_box', 'Squat box unilateral (pistol)', 2, '9/pierna', 90),
      ]
    },
    // S2
    {
      1: [
        _ex('c5k_m_balanceo', 'Movilidad | Balanceo de piernas', 1, '10/pierna', 0),
        _ex('c5k_m_flex_sed', 'Movilidad | Flexión de tobillo sedestación', 1, '10/pierna', 0),
        _ex('c5k_m_squat_rod','Sentadilla + rodilla al pecho', 1, '5/lado', 0),
        _ex('c5k_caco',       'Correr (Ca-Co)', 6, '1 min correr + 4 min andar', 0, '30 min total'),
      ],
      3: [
        _ex('c5k_m_hip_car',  'Movilidad | Hip CAR', 1, '10/pierna', 0),
        _ex('c5k_m_flex_bip', 'Movilidad | Flexión de tobillo bipedestación', 1, '8/lado', 0),
        _ex('c5k_m_balanceo', 'Movilidad | Balanceo de piernas', 1, '10/pierna', 0),
        _ex('c5k_caco',       'Correr (Ca-Co)', 7, '1 min correr + 3 min andar', 0, '28 min total'),
      ],
      4: [
        _ex('c5k_m_rockback', 'Movilidad | Leg Rockback', 2, '9/lado', 90),
        _ex('c5k_m_flex_sed', 'Movilidad | Flexión de tobillo sedestación', 2, '9/lado', 90),
        _ex('c5k_gemelo_mc',  'Gemelo con mancuernas sentada', 2, '9', 90),
      ],
      5: [
        _ex('c5k_m_rlunge', 'Movilidad | Runners lunge', 1, '8/lado', 0),
        _ex('c5k_caco',     'Correr (Ca-Co)', 10, '1 min correr + 2 min andar', 0, '30 min total'),
      ],
      6: [
        _ex('c5k_m_rockback', 'Movilidad | Leg Rockback', 2, '9/lado', 90),
        _ex('c5k_ext_dedo',   'Extensión del dedo gordo', 2, '9/lado', 90),
        _ex('c5k_gemelo_mc',  'Gemelo con mancuernas sentada', 2, '9/lado', 90),
        _ex('c5k_fr_cuad',    'Foam roller | Cuádriceps', 2, '9', 90),
        _ex('c5k_step_up',    'Step up con mancuerna', 2, '9/pierna', 90),
        _ex('c5k_pistol_box', 'Squat box unilateral (pistol)', 2, '9/pierna', 90),
      ]
    },
    // S3
    {
      1: [
        _ex('c5k_m_balanceo', 'Movilidad | Balanceo de piernas', 1, '10/pierna', 0),
        _ex('c5k_m_flex_sed', 'Movilidad | Flexión de tobillo sedestación', 1, '10/pierna', 0),
        _ex('c5k_m_squat_rod','Sentadilla + rodilla al pecho', 1, '5/lado', 0),
        _ex('c5k_caco',       'Correr (Ca-Co)', 3, '2 min correr + 9 min andar', 0, '33 min total'),
      ],
      3: [
        _ex('c5k_m_hip_car',  'Movilidad | Hip CAR', 1, '10/pierna', 0),
        _ex('c5k_m_flex_bip', 'Movilidad | Flexión de tobillo bipedestación', 1, '8/lado', 0),
        _ex('c5k_m_balanceo', 'Movilidad | Balanceo de piernas', 1, '10/pierna', 0),
        _ex('c5k_caco',       'Correr (Ca-Co)', 3, '2 min correr + 8 min andar', 0, '30 min total'),
      ],
      4: [
        _ex('c5k_m_rockback', 'Movilidad | Leg Rockback', 2, '9/lado', 90),
        _ex('c5k_m_flex_sed', 'Movilidad | Flexión de tobillo sedestación', 2, '9/lado', 90),
        _ex('c5k_gemelo_mc',  'Gemelo con mancuernas sentada', 2, '9', 90),
      ],
      5: [
        _ex('c5k_m_rlunge', 'Movilidad | Runners lunge', 1, '8/lado', 0),
        _ex('c5k_caco',     'Correr (Ca-Co)', 4, '2 min correr + 6 min andar', 0, '32 min total'),
      ],
      6: [
        _ex('c5k_m_rockback', 'Movilidad | Leg Rockback', 2, '9/lado', 90),
        _ex('c5k_ext_dedo',   'Extensión del dedo gordo', 2, '9/lado', 90),
        _ex('c5k_gemelo_mc',  'Gemelo con mancuernas sentada', 2, '9/lado', 90),
        _ex('c5k_fr_cuad',    'Foam roller | Cuádriceps', 2, '9', 90),
        _ex('c5k_step_up',    'Step up con mancuerna', 2, '9/pierna', 90),
        _ex('c5k_pistol_box', 'Squat box unilateral (pistol)', 2, '9/pierna', 90),
      ]
    }
  ]
};

/* ══════════════ QUEMA GRASA COMPLEMENTO (8 semanas) ══════════════ */
WORKOUT_PLANS.quema_grasa_comp = {
  id: 'quema_grasa_comp',
  name: 'Quema Grasa Complemento',
  planType: 'phased',
  weeks: 8,
  description: 'Programa complementario 8 sem — cardio/HIIT/sprints/natación',
  trainingDays: [1, 2, 3, 4, 5, 6],
  dayMeta: {
    1: { name: 'Comba / Caminar inclinación', type: 'strength', muscleGroups: ['Cardio', 'Piernas'] },
    2: { name: 'Caminar con lastre',          type: 'strength', muscleGroups: ['Cardio'] },
    3: { name: 'HIIT en casa/gym',            type: 'strength', muscleGroups: ['Full body', 'Cardio'] },
    4: { name: 'Stairmaster',                 type: 'strength', muscleGroups: ['Cardio', 'Piernas'] },
    5: { name: 'Sprints / Bici',              type: 'strength', muscleGroups: ['Cardio', 'Piernas'] },
    6: { name: 'Natación',                    type: 'strength', muscleGroups: ['Cardio', 'Full body'] }
  },
  weeklySchedule: [
    // S1 (impar)
    {
      1: [ _ex('qgc_comba', 'Salto a la comba', 5, '30s', 60) ],
      3: [
        _ex('qgc_burpees',    'HIIT | Burpees', 2, '12', 30),
        _ex('qgc_curtsy',     'HIIT | Curtsy jumps', 2, '10/lado', 30),
        _ex('qgc_jjacks',     'HIIT | Jumping jacks', 2, '12', 30),
        _ex('qgc_prisside',   'HIIT | Prisioner side to side squats', 2, '12', 30),
        _ex('qgc_tuck',       'HIIT | Tuck jumps', 2, '10', 30),
        _ex('qgc_walkout',    'HIIT | Walkout jump', 2, '12', 30),
        _ex('qgc_latlunge',   'HIIT | Lateral lunge drop', 2, '12', 30),
        _ex('qgc_squatrot',   'HIIT | Sentadilla con salto + rotación', 2, '10', 30),
      ],
      5: [ _ex('qgc_sprint', 'Correr | Sprint', 4, '300m (7/8)', 90) ]
    },
    // S2 (par)
    {
      1: [ _ex('qgc_caminc',    'Caminar con inclinación (cinta)', 1, '30 min (3mph, 12%)', 0) ],
      2: [ _ex('qgc_camlastre', 'Caminar con lastre', 1, '30 min', 0, '~7% peso corporal') ],
      4: [ _ex('qgc_stair',     'Stairmaster', 1, '20-30 min', 0, 'NVL 7-9') ],
      5: [ _ex('qgc_bici',      'Bicicleta estática (intervalos)', 4, '60s al 85-90% FCmax', 60) ],
      6: [
        _ex('qgc_nat_suave', 'Natación | Nadar suave', 4, '25m', 0),
        _ex('qgc_nat_int',   'Natación | Intervalos 65-85% FCmax', 2, '25m x 2', 45, '2 min entre bloques'),
        _ex('qgc_nat_cool',  'Natación | Nado relajado', 1, '100m', 0),
      ]
    },
    // S3 (impar)
    {
      1: [ _ex('qgc_comba', 'Salto a la comba', 5, '1 min', 60) ],
      3: [
        _ex('qgc_benchover',   'HIIT | Bench over jumps', 2, '12', 30),
        _ex('qgc_jjacks',      'HIIT | Jumping jacks', 2, '12', 30),
        _ex('qgc_prisknee',    'HIIT | Prisioner squat + knee in', 2, '10', 30),
        _ex('qgc_tuck',        'HIIT | Tuck jumps', 2, '10', 30),
        _ex('qgc_lunge',       'HIIT | Lunge jump', 1, '12', 30),
        _ex('qgc_prisside',    'HIIT | Prisioner side to side squats', 2, '10', 30),
        _ex('qgc_calf',        'HIIT | Calf jumps', 2, '12', 30),
        _ex('qgc_plankthrust', 'HIIT | Plank thrust', 2, '12', 30),
      ],
      5: [ _ex('qgc_sprint', 'Correr | Sprint', 4, '400m (7/8)', 120) ]
    },
    // S4 (par)
    {
      1: [ _ex('qgc_caminc',    'Caminar con inclinación (cinta)', 1, '30 min (3mph, 12%)', 0) ],
      2: [ _ex('qgc_camlastre', 'Caminar con lastre', 1, '30 min', 0, '~8% peso corporal') ],
      4: [ _ex('qgc_stair',     'Stairmaster', 1, '25-30 min', 0, 'NVL 7-9') ],
      5: [ _ex('qgc_bici',      'Bicicleta estática (intervalos)', 4, '90s al 85-90% FCmax', 60) ],
      6: [
        _ex('qgc_nat_suave', 'Natación | Nadar suave', 4, '25m', 0),
        _ex('qgc_nat_int',   'Natación | Intervalos 65-85% FCmax', 3, '25m x 3', 45, '2 min entre bloques'),
        _ex('qgc_nat_cool',  'Natación | Nado relajado', 1, '100m', 0),
      ]
    },
    // S5 (impar)
    {
      1: [ _ex('qgc_comba', 'Salto a la comba', 5, '90s', 60) ],
      3: [
        _ex('qgc_burpees',   'HIIT | Burpees', 2, '14', 30),
        _ex('qgc_curtsy',    'HIIT | Curtsy jumps', 2, '14/lado', 30),
        _ex('qgc_jjacks',    'HIIT | Jumping jacks', 2, '15', 30),
        _ex('qgc_prisside',  'HIIT | Prisioner side to side squats', 2, '15', 30),
        _ex('qgc_tuck',      'HIIT | Tuck jumps', 2, '12', 30),
        _ex('qgc_walkout',   'HIIT | Walkout jump', 2, '15', 30),
        _ex('qgc_latlunge',  'HIIT | Lateral lunge drop', 2, '15', 30),
        _ex('qgc_squatrot',  'HIIT | Sentadilla con salto + rotación', 2, '15', 30),
      ],
      5: [ _ex('qgc_sprint', 'Correr | Sprint', 4, '400m (7/8)', 60) ]
    },
    // S6 (par)
    {
      1: [ _ex('qgc_caminc',    'Caminar con inclinación (cinta)', 1, '30 min (3mph, 12%)', 0) ],
      2: [ _ex('qgc_camlastre', 'Caminar con lastre', 1, '30 min', 0, '~10% peso corporal') ],
      4: [ _ex('qgc_stair',     'Stairmaster', 1, '25-30 min', 0, 'NVL 8-9') ],
      5: [ _ex('qgc_bici',      'Bicicleta estática (intervalos)', 5, '90s al 85-90% FCmax', 60) ],
      6: [
        _ex('qgc_nat_suave', 'Natación | Nadar suave', 4, '25m', 0),
        _ex('qgc_nat_int',   'Natación | Intervalos 65-85% FCmax', 3, '25m x 3', 30, '2 min entre bloques'),
        _ex('qgc_nat_cool',  'Natación | Nado relajado', 1, '100m', 0),
      ]
    },
    // S7 (impar)
    {
      1: [ _ex('qgc_comba', 'Salto a la comba', 6, '1 min', 30) ],
      3: [
        _ex('qgc_benchover',   'HIIT | Bench over jumps', 3, '10', 20),
        _ex('qgc_jjacks',      'HIIT | Jumping jacks', 3, '10', 20),
        _ex('qgc_prisknee',    'HIIT | Prisioner squat + knee in', 3, '10', 20),
        _ex('qgc_tuck',        'HIIT | Tuck jumps', 3, '10', 20),
        _ex('qgc_lunge',       'HIIT | Lunge jump', 3, '10', 20),
        _ex('qgc_prisside',    'HIIT | Prisioner side to side squats', 3, '10', 20),
        _ex('qgc_calf',        'HIIT | Calf jumps', 3, '10', 20),
        _ex('qgc_plankthrust', 'HIIT | Plank thrust', 3, '10', 20),
      ],
      5: [ _ex('qgc_sprint', 'Correr | Sprint', 5, '400m (7/8)', 120) ]
    },
    // S8 (par)
    {
      1: [ _ex('qgc_caminc',    'Caminar con inclinación (cinta)', 1, '30 min (3mph, 12%)', 0) ],
      2: [ _ex('qgc_camlastre', 'Caminar con lastre', 1, '30 min', 0, '~11% peso corporal') ],
      4: [ _ex('qgc_stair',     'Stairmaster', 1, '30 min', 0, 'NVL 8-9') ],
      5: [ _ex('qgc_bici',      'Bicicleta estática (intervalos)', 5, '90s al 85-90% FCmax', 30) ],
      6: [
        _ex('qgc_nat_suave', 'Natación | Nadar suave', 4, '25m', 0),
        _ex('qgc_nat_int',   'Natación | Intervalos 65-85% FCmax', 4, '25m x 4', 30, '90s entre bloques'),
        _ex('qgc_nat_cool',  'Natación | Nado relajado', 1, '100m', 0),
      ]
    }
  ]
};

/* ══════════════ PÉRDIDA DE GRASA (12 semanas) ══════════════ */
WORKOUT_PLANS.perdida_grasa = {
  id: 'perdida_grasa',
  name: 'Pérdida de Grasa',
  planType: 'phased',
  weeks: 12,
  description: 'Programa de 12 semanas para pérdida de grasa (Fase 1: 5 días/sem · Fase 2: 6 días/sem)',
  trainingDays: [1, 2, 3, 4, 5, 6],
  dayMeta: {
    1: { name: 'Pierna (Glúteo)',   type: 'strength', muscleGroups: ['Glúteos', 'Cuádriceps', 'Core'] },
    2: { name: 'Torso + cardio',    type: 'strength', muscleGroups: ['Espalda', 'Hombros', 'Pecho', 'Brazos', 'Cardio'] },
    3: { name: 'Pierna (Femoral)',  type: 'strength', muscleGroups: ['Isquios', 'Glúteos', 'Gemelos', 'Core'] },
    4: { name: 'Cardio LISS',       type: 'running',  muscleGroups: ['Cardio'] },
    5: { name: 'Full body',         type: 'strength', muscleGroups: ['Full body', 'Hombros', 'Glúteos'] },
    6: { name: 'HIIT',              type: 'strength', muscleGroups: ['Cardio', 'Core'] }
  },
  weeklySchedule: [
    // ───── FASE 1 (semanas 1-6, 5 días/sem) ─────
    // S1
    {
      1: [
        _ex('pdg_m_cat_camel',  'Movilidad | Cat camel', 1, '10', 0),
        _ex('pdg_m_cossak',     'Movilidad | Cossak squat', 1, '8/lado', 0),
        _ex('pdg_m_flex_peso',  'Movilidad | Flexión de tobillo con peso', 1, '30s/lado', 0),
        _ex('pdg_abd_iso',      'Abducción de cadera isométrica con resistencia', 8, '10s iso + 10s desc', 0),
        _ex('pdg_ht_aprox',     'Hip Thrust (aproximación)', 2, '6', 60),
        _ex('pdg_ht',           'Hip Thrust', 2, '8/10', 60),
        _ex('pdg_sq_rebote',    'Sentadilla con rebote', 2, '10', 60),
        _ex('pdg_bulg_mp',      'Sentadilla búlgara en multipower', 2, '10-12', 60),
        _ex('pdg_box_jumps',    'Box jumps | Progresión', 3, '6-8', 30),
        _ex('pdg_ball_wall',    'Ball wall lateral', 2, '10', 30),
        _ex('pdg_core_pl_dist', 'Core | Plancha con manos distanciadas', 2, '40s', 20),
      ],
      2: [
        _ex('pdg_m_snow',       'Movilidad | Prone snow angels', 1, '10', 0),
        _ex('pdg_m_rlunge_r',   'Movilidad | Runners lunge with reach', 1, '6/lado', 0),
        _ex('pdg_m_rot_hum',    'Movilidad | Rotación humeral con peso', 1, '8/lado', 0),
        _ex('pdg_flex_plio',    'Flexiones pliométricas con altura', 2, 'Máximas', 38),
        _ex('pdg_jalon_uni',    'Jalón unilateral en polea', 3, '14', 60),
        _ex('pdg_press_hom_mc', 'Press de hombro con mancuernas', 3, '10/14', 60),
        _ex('pdg_elev_lat_mc',  'Elevaciones laterales con mancuernas', 3, '12', 45),
        _ex('pdg_remo_seal',    'Remo seal', 3, '12', 60),
        _ex('pdg_curl_bic_mc',  'Curl de bíceps con mancuerna', 3, '14', 45),
        _ex('pdg_skull',        'Skull crusher', 3, '14', 45),
        _ex('pdg_liss_torso',   'Cardio LISS', 1, '15 min (5+5+5)', 0, 'Baja/moderada/baja'),
      ],
      3: [
        _ex('pdg_m_rockback',   'Movilidad | Leg Rockback', 1, '8/lado', 0),
        _ex('pdg_m_standing',   'Movilidad | Standing reach down fwd-back', 1, '6', 0),
        _ex('pdg_hiperext',     'Hiperextensión', 2, '16', 30),
        _ex('pdg_pmr_uni_mc',   'Peso muerto rumano unilateral con mancuernas', 3, '10/12', 60),
        _ex('pdg_skier',        'Skier swings con disco', 3, '8', 60),
        _ex('pdg_pat_glut_pol', 'Patada de glúteo en polea', 2, '14', 60),
        _ex('pdg_curl_femoral', 'Curl de femoral', 2, '14', 60),
        _ex('pdg_soleo_mc',     'Sóleo sentado con mancuernas', 3, '20', 60),
        _ex('pdg_core_pl_inv',  'Core | Plancha inversa con toques de rodilla', 2, '30s', 30),
        _ex('pdg_core_rtwist',  'Core | Russian twist con disco', 2, '20', 30),
      ],
      5: [
        _ex('pdg_ht_uni_sp',     'Hip thrust unilateral sin peso', 2, '14', 0),
        _ex('pdg_pm_sumo_aprox', 'Peso muerto sumo (aproximación)', 2, '6', 60),
        _ex('pdg_pm_sumo',       'Peso muerto sumo', 3, '8', 90),
        _ex('pdg_landmine',      'Landmine thruster', 3, '10', 60),
        _ex('pdg_aus_pullups',   'Australian pull-ups', 2, '10-12', 60),
        _ex('pdg_elev_lf_mc',    'Elevaciones laterales + frontales con mancuernas', 3, '12', 45),
        _ex('pdg_delt_post_pol', 'Deltoides posterior en polea', 3, '15', 60),
        _ex('pdg_salt_lat_cj',   'Saltos laterales al cajón | Progresión', 2, '6-8', 53),
        _ex('pdg_samurai_pol',   'Samurai pulls en polea', 2, '16', 60),
        _ex('pdg_core_elev_col', 'Core | Elevación de piernas colgada', 2, '10', 30),
      ],
      6: [
        _ex('pdg_hiit_sq_toes',  'HIIT | Sentadilla + toques de pie', 3, '30s', 30),
        _ex('pdg_hiit_pl_thrust','HIIT | Plank thrust', 3, '30s', 30),
        _ex('pdg_hiit_pulse_js', 'HIIT | Pulse jump squats', 3, '30s', 30),
        _ex('pdg_core_dolphin',  'Core | Dolphin plank + knee taps', 3, '30s', 30),
        _ex('pdg_hiit_calf',     'HIIT | Calf jumps', 3, '30s', 30),
      ]
    },
    // S2
    {
      1: [
        _ex('pdg_m_cat_camel',  'Movilidad | Cat camel', 1, '10', 0),
        _ex('pdg_m_cossak',     'Movilidad | Cossak squat', 1, '8/lado', 0),
        _ex('pdg_m_flex_peso',  'Movilidad | Flexión de tobillo con peso', 1, '30s/lado', 0),
        _ex('pdg_abd_iso',      'Abducción de cadera isométrica con resistencia', 8, '15s iso', 10),
        _ex('pdg_ht_aprox',     'Hip Thrust (aproximación)', 2, '6', 60),
        _ex('pdg_ht',           'Hip Thrust', 3, '8/10', 90),
        _ex('pdg_sq_rebote',    'Sentadilla con rebote', 2, '10', 60),
        _ex('pdg_bulg_mp',      'Sentadilla búlgara en multipower', 3, '8-12', 75),
        _ex('pdg_box_jumps',    'Box jumps | Progresión', 3, '6-8', 38),
        _ex('pdg_core_pike',    'Core | Pike plank en fitball', 2, '8', 30),
        _ex('pdg_core_kb_wm',   'Core | KB Windmill', 2, '12', 30),
      ],
      2: [
        _ex('pdg_m_snow',       'Movilidad | Prone snow angels', 1, '10', 0),
        _ex('pdg_m_rlunge_r',   'Movilidad | Runners lunge with reach', 1, '6/lado', 0),
        _ex('pdg_m_rot_hum',    'Movilidad | Rotación humeral con peso', 1, '8/lado', 0),
        _ex('pdg_flex_plio',    'Flexiones pliométricas con altura', 3, 'Máximas (10-12)', 53),
        _ex('pdg_jalon_uni',    'Jalón unilateral en polea', 4, '14', 60),
        _ex('pdg_press_hom_uni','Press de hombro unilateral', 3, '14', 60),
        _ex('pdg_elev_lat_mc',  'Elevaciones laterales con mancuernas', 4, '12', 45),
        _ex('pdg_remo_seal',    'Remo seal', 3, '12', 60),
        _ex('pdg_curl_bic_mc',  'Curl de bíceps con mancuerna', 3, '14', 60),
        _ex('pdg_skull',        'Skull crusher', 3, '14', 60),
        _ex('pdg_liss_torso',   'Cardio LISS', 1, '17 min (5+7+5)', 0),
      ],
      3: [
        _ex('pdg_m_rockback',   'Movilidad | Leg Rockback', 1, '8/lado', 0),
        _ex('pdg_m_standing',   'Movilidad | Standing reach down fwd-back', 1, '6', 0),
        _ex('pdg_hiperext',     'Hiperextensión', 2, '16', 40),
        _ex('pdg_pmr_uni_mc',   'Peso muerto rumano unilateral con mancuernas', 3, '10/12', 60),
        _ex('pdg_skier',        'Skier swings con disco', 3, '10', 60),
        _ex('pdg_pat_glut_pol', 'Patada de glúteo en polea', 2, '14', 60),
        _ex('pdg_curl_femoral', 'Curl de femoral', 3, '14', 60),
        _ex('pdg_gemelo_prensa','Gemelo en prensa', 3, '15', 60),
        _ex('pdg_core_cr_res',  'Core | Crunch abdominal con resistencia', 2, '16', 30),
        _ex('pdg_core_rolls',   'Core | Rollouts con barra', 2, '6', 30),
      ],
      5: [
        _ex('pdg_ht_uni_sp',     'Hip thrust unilateral sin peso', 3, '14', 20),
        _ex('pdg_pm_sumo_aprox', 'Peso muerto sumo (aproximación)', 2, '4', 30),
        _ex('pdg_pm_sumo',       'Peso muerto sumo', 3, '6/8', 75),
        _ex('pdg_landmine',      'Landmine thruster', 3, '10', 60),
        _ex('pdg_remo_gir_pol',  'Remo gironda en polea', 2, '10-12', 60),
        _ex('pdg_elev_lf_mc',    'Elevaciones laterales + frontales con mancuernas', 4, '12', 30),
        _ex('pdg_delt_post_pol', 'Deltoides posterior en polea', 3, '15', 60),
        _ex('pdg_salt_lat_cj',   'Saltos laterales al cajón | Progresión', 2, '8-10', 38),
        _ex('pdg_core_rolls',    'Core | Rollouts con barra', 2, '6', 30),
      ],
      6: [
        _ex('pdg_hiit_lunge_d',  'HIIT | Lunge drop', 3, '30s', 30),
        _ex('pdg_hiit_bench_j',  'HIIT | Bench over jumps', 3, '30s', 30),
        _ex('pdg_hiit_walk_piv', 'HIIT | Walking pivot squats', 3, '30s', 30),
        _ex('pdg_core_pl_inv',   'Core | Plancha inversa con toques de rodilla', 3, '30s', 30),
        _ex('pdg_hiit_fast_feet','HIIT | Fast feet', 3, '30s', 30),
      ]
    },
    // S3
    {
      1: [
        _ex('pdg_m_cat_camel',  'Movilidad | Cat camel', 1, '10', 0),
        _ex('pdg_m_cossak',     'Movilidad | Cossak squat', 1, '8/lado', 0),
        _ex('pdg_m_flex_peso',  'Movilidad | Flexión de tobillo con peso', 1, '30s/lado', 0),
        _ex('pdg_abd_iso',      'Abducción de cadera isométrica con resistencia', 8, '15s iso + 10s desc', 0),
        _ex('pdg_ht_aprox',     'Hip Thrust (aproximación)', 2, '6', 45),
        _ex('pdg_ht',           'Hip Thrust', 3, '8/10 (último al fallo)', 90),
        _ex('pdg_sq_rebote',    'Sentadilla con rebote', 2, '10', 30),
        _ex('pdg_bulg_mp',      'Sentadilla búlgara en multipower', 3, '8-12', 75),
        _ex('pdg_box_jumps',    'Box jumps | Progresión', 3, '8', 45),
        _ex('pdg_ball_wall',    'Ball wall lateral', 2, '10', 30),
        _ex('pdg_core_pl_dist', 'Core | Plancha con manos distanciadas', 2, '45s', 20),
      ],
      2: [
        _ex('pdg_m_snow',       'Movilidad | Prone snow angels', 1, '10', 0),
        _ex('pdg_m_rlunge_r',   'Movilidad | Runners lunge with reach', 1, '6/lado', 0),
        _ex('pdg_m_rot_hum',    'Movilidad | Rotación humeral con peso', 1, '8/lado', 0),
        _ex('pdg_flex_plio',    'Flexiones pliométricas con altura', 3, 'Máximas (10-12)', 53),
        _ex('pdg_jalon_uni',    'Jalón unilateral en polea', 4, '14', 60),
        _ex('pdg_press_hom_mc', 'Press de hombro con mancuernas', 3, '14', 60),
        _ex('pdg_elev_lat_mc',  'Elevaciones laterales con mancuernas', 4, '12', 60),
        _ex('pdg_remo_seal',    'Remo seal', 3, '12', 60),
        _ex('pdg_curl_bic_mc',  'Curl de bíceps con mancuerna', 3, '14', 60),
        _ex('pdg_skull',        'Skull crusher', 3, '14', 60),
        _ex('pdg_liss_torso',   'Cardio LISS', 1, '20 min (5+10+5)', 0),
      ],
      3: [
        _ex('pdg_m_rockback',     'Movilidad | Leg Rockback', 1, '8/lado', 0),
        _ex('pdg_m_standing',     'Movilidad | Standing reach down fwd-back', 1, '6', 0),
        _ex('pdg_hiperext',       'Hiperextensión', 2, '16', 30),
        _ex('pdg_sent_libre_ap',  'Sentadilla libre | barra alta (aproximación)', 2, '6-8', 60),
        _ex('pdg_sent_libre',     'Sentadilla libre | barra alta', 3, '6', 90),
        _ex('pdg_pmr_uni_mc',     'Peso muerto rumano unilateral con mancuernas', 2, '10', 45),
        _ex('pdg_skier',          'Skier swings con disco', 3, '10', 60),
        _ex('pdg_pat_glut_pol',   'Patada de glúteo en polea', 2, '14', 60),
        _ex('pdg_curl_femoral',   'Curl de femoral', 3, '14', 60),
        _ex('pdg_soleo_mc',       'Sóleo sentado con mancuernas', 3, '20', 60),
        _ex('pdg_core_pl_inv',    'Core | Plancha inversa con toques de rodilla', 2, '30s', 30),
        _ex('pdg_core_rtwist',    'Core | Russian twist con disco', 2, '20', 30),
      ],
      5: [
        _ex('pdg_ht_uni_sp',     'Hip thrust unilateral sin peso', 3, '14', 0),
        _ex('pdg_pm_sumo_aprox', 'Peso muerto sumo (aproximación)', 2, '4', 45),
        _ex('pdg_pm_sumo',       'Peso muerto sumo', 3, '6/8', 75),
        _ex('pdg_landmine',      'Landmine thruster', 3, '12', 60),
        _ex('pdg_aus_pullups',   'Australian pull-ups', 2, '10-12', 60),
        _ex('pdg_elev_lf_mc',    'Elevaciones laterales + frontales con mancuernas', 4, '12', 60),
        _ex('pdg_delt_post_pol', 'Deltoides posterior en polea', 3, '15', 60),
        _ex('pdg_salt_lat_cj',   'Saltos laterales al cajón | Progresión', 2, '8-10', 38),
        _ex('pdg_samurai_pol',   'Samurai pulls en polea', 2, '16', 60),
        _ex('pdg_core_elev_col', 'Core | Elevación de piernas colgada', 2, '10', 30),
      ],
      6: [
        _ex('pdg_hiit_prisside',  'HIIT | Prisioner side to side squats', 3, '30s', 30),
        _ex('pdg_core_dolphin',   'Core | Dolphin plank + knee taps', 3, '30s', 30),
        _ex('pdg_hiit_scissor',   'HIIT | Scissor jumps', 3, '30s', 30),
        _ex('pdg_core_toe_taps',  'Core | Toe taps', 3, '30s', 30),
        _ex('pdg_hiit_rocket',    'HIIT | Rocket launch squats', 3, '30s', 30),
      ]
    },
    // S4
    {
      1: [
        _ex('pdg_m_cat_camel',  'Movilidad | Cat camel', 1, '10', 0),
        _ex('pdg_m_cossak',     'Movilidad | Cossak squat', 1, '8/lado', 0),
        _ex('pdg_m_flex_peso',  'Movilidad | Flexión de tobillo con peso', 1, '30s/lado', 0),
        _ex('pdg_abd_iso',      'Abducción de cadera isométrica con resistencia', 8, '20s iso + 10s desc', 0),
        _ex('pdg_ht_aprox',     'Hip Thrust (aproximación)', 2, '6', 40),
        _ex('pdg_ht',           'Hip Thrust', 3, '8/10', 90),
        _ex('pdg_sq_rebote',    'Sentadilla con rebote', 2, '10', 30),
        _ex('pdg_bulg_mp',      'Sentadilla búlgara en multipower', 3, '8-12', 75),
        _ex('pdg_box_jumps',    'Box jumps | Progresión', 3, '8-10', 45),
        _ex('pdg_core_pike',    'Core | Pike plank en fitball', 2, '10', 30),
        _ex('pdg_core_kb_wm',   'Core | KB Windmill', 2, '12', 30),
      ],
      2: [
        _ex('pdg_m_snow',       'Movilidad | Prone snow angels', 1, '10', 0),
        _ex('pdg_m_rlunge_r',   'Movilidad | Runners lunge with reach', 1, '6/lado', 0),
        _ex('pdg_m_rot_hum',    'Movilidad | Rotación humeral con peso', 1, '8/lado', 0),
        _ex('pdg_flex_plio',    'Flexiones pliométricas con altura', 3, 'Máximas (10-12)', 53),
        _ex('pdg_jalon_uni',    'Jalón unilateral en polea', 4, '14', 60),
        _ex('pdg_press_hom_mc', 'Press de hombro con mancuernas', 3, '14', 60),
        _ex('pdg_elev_lat_mc',  'Elevaciones laterales con mancuernas', 4, '12', 60),
        _ex('pdg_remo_seal',    'Remo seal', 3, '12', 60),
        _ex('pdg_curl_bic_mc',  'Curl de bíceps con mancuerna', 3, '14', 60),
        _ex('pdg_skull',        'Skull crusher', 3, '14', 60),
        _ex('pdg_liss_torso',   'Cardio LISS', 1, '20 min (5+10+5)', 0),
      ],
      3: [
        _ex('pdg_m_rockback',     'Movilidad | Leg Rockback', 1, '8/lado', 0),
        _ex('pdg_m_standing',     'Movilidad | Standing reach down fwd-back', 1, '6', 0),
        _ex('pdg_hiperext',       'Hiperextensión', 2, '16', 30),
        _ex('pdg_sent_libre_ap',  'Sentadilla libre | barra alta (aproximación)', 2, '6-8', 60),
        _ex('pdg_sent_libre',     'Sentadilla libre | barra alta', 3, '6', 90),
        _ex('pdg_pmr_uni_mc',     'Peso muerto rumano unilateral con mancuernas', 2, '10', 45),
        _ex('pdg_skier',          'Skier swings con disco', 3, '10', 60),
        _ex('pdg_pat_glut_pol',   'Patada de glúteo en polea', 2, '14', 60),
        _ex('pdg_curl_femoral',   'Curl de femoral', 3, '14', 60),
        _ex('pdg_gemelo_prensa',  'Gemelo en prensa', 3, '15', 60),
        _ex('pdg_core_cr_res',    'Core | Crunch abdominal con resistencia', 2, '16', 30),
        _ex('pdg_core_rolls',     'Core | Rollouts con barra', 2, '6-8', 30),
      ],
      5: [
        _ex('pdg_ht_uni_sp',      'Hip thrust unilateral sin peso', 3, '14', 0),
        _ex('pdg_pm_sumo_aprox',  'Peso muerto sumo (aproximación)', 2, '4', 30),
        _ex('pdg_pm_sumo',        'Peso muerto sumo', 3, '6/8', 75),
        _ex('pdg_landmine',       'Landmine thruster', 3, '12', 60),
        _ex('pdg_remo_gir_pol',   'Remo gironda en polea', 3, '10-12', 90),
        _ex('pdg_press_banc_mc',  'Press banca inclinado con mancuernas', 4, '14', 90),
        _ex('pdg_remo_menton',    'Remo al mentón en polea', 4, '12', 60),
        _ex('pdg_delt_post_pol',  'Deltoides posterior en polea', 3, '15', 60),
        _ex('pdg_salt_lat_cj',    'Saltos laterales al cajón | Progresión', 2, '10', 30),
        _ex('pdg_core_mcgill',    'Core | McGill crunch', 2, '16', 30),
        _ex('pdg_samurai_banded', 'Samurai banded pulls', 2, '20', 30),
      ],
      6: [
        _ex('pdg_hiit_lat_ld',    'HIIT | Lateral lunge drop', 3, '30s', 30),
        _ex('pdg_hiit_pl_thrust', 'HIIT | Plank thrust', 3, '30s', 30),
        _ex('pdg_hiit_side_bound','HIIT | Side bound launches', 3, '30s', 30),
        _ex('pdg_core_mt_clm',    'Core | Mountain climbers', 3, '30s', 30),
        _ex('pdg_hiit_rocket_tap','HIIT | Rocket launch taps', 3, '30s', 30),
      ]
    },
    // S5
    {
      1: [
        _ex('pdg_m_cat_camel',  'Movilidad | Cat camel', 1, '10', 0),
        _ex('pdg_m_cossak',     'Movilidad | Cossak squat', 1, '8/lado', 0),
        _ex('pdg_m_flex_peso',  'Movilidad | Flexión de tobillo con peso', 1, '30s/lado', 0),
        _ex('pdg_abd_iso',      'Abducción de cadera isométrica con resistencia', 8, '20s iso', 10),
        _ex('pdg_ht_aprox',     'Hip Thrust (aproximación)', 2, '6', 45),
        _ex('pdg_ht',           'Hip Thrust', 3, '8/10', 90),
        _ex('pdg_sq_rebote',    'Sentadilla con rebote', 2, '10', 60),
        _ex('pdg_bulg_mp',      'Sentadilla búlgara en multipower', 3, '8-12', 90),
        _ex('pdg_box_jumps',    'Box jumps | Progresión', 3, '10', 30),
        _ex('pdg_core_pike',    'Core | Pike plank en fitball', 2, '10', 30),
        _ex('pdg_core_kb_wm',   'Core | KB Windmill', 2, '12', 30),
      ],
      2: [
        _ex('pdg_m_snow',        'Movilidad | Prone snow angels', 1, '10', 0),
        _ex('pdg_m_rlunge_r',    'Movilidad | Runners lunge with reach', 1, '6/lado', 0),
        _ex('pdg_m_rot_hum',     'Movilidad | Rotación humeral con peso', 1, '8/lado', 0),
        _ex('pdg_flex_plio',     'Flexiones pliométricas con altura', 3, 'Máximas (12-14)', 60),
        _ex('pdg_jalon_uni',     'Jalón unilateral en polea', 4, '14', 60),
        _ex('pdg_press_hom_mc',  'Press de hombro con mancuernas', 4, '14', 60),
        _ex('pdg_elev_lat_drop', 'Elevaciones laterales - Drop set', 3, '12', 60, 'Descansa 2 min tras cada drop'),
        _ex('pdg_remo_seal',     'Remo seal', 4, '12', 60),
        _ex('pdg_curl_bic_mc',   'Curl de bíceps con mancuerna', 4, '14', 60),
        _ex('pdg_skull',         'Skull crusher', 4, '14', 60),
        _ex('pdg_liss_torso',    'Cardio LISS', 1, '27 min (5+17+5)', 0),
      ],
      3: [
        _ex('pdg_m_rockback',     'Movilidad | Leg Rockback', 1, '8/lado', 0),
        _ex('pdg_m_standing',     'Movilidad | Standing reach down fwd-back', 1, '6', 0),
        _ex('pdg_hiperext',       'Hiperextensión', 2, '16', 30),
        _ex('pdg_sent_libre_ap',  'Sentadilla libre | barra alta (aproximación)', 2, '6-8', 38),
        _ex('pdg_sent_libre',     'Sentadilla libre | barra alta', 3, '6', 90),
        _ex('pdg_pmr_uni_mc',     'Peso muerto rumano unilateral con mancuernas', 2, '10', 60),
        _ex('pdg_skier',          'Skier swings con disco', 3, '12', 60),
        _ex('pdg_pat_glut_pol',   'Patada de glúteo en polea', 3, '14 - fallo', 90),
        _ex('pdg_curl_femoral',   'Curl de femoral', 3, '14 - fallo', 90),
        _ex('pdg_gemelo_prensa',  'Gemelo en prensa', 3, '15 - fallo', 90),
        _ex('pdg_core_cr_res',    'Core | Crunch abdominal con resistencia', 2, '16', 30),
        _ex('pdg_core_rolls',     'Core | Rollouts con barra', 2, '6-8', 30),
      ],
      5: [
        _ex('pdg_ht_uni_sp',      'Hip thrust unilateral sin peso', 3, '14', 0),
        _ex('pdg_pm_sumo_aprox',  'Peso muerto sumo (aproximación)', 2, '4', 45),
        _ex('pdg_pm_sumo',        'Peso muerto sumo', 3, '6/8', 75),
        _ex('pdg_landmine',       'Landmine thruster', 3, '12', 60),
        _ex('pdg_remo_gir_pol',   'Remo gironda en polea', 3, '10-12 fallo', 90),
        _ex('pdg_press_banc_mc',  'Press banca inclinado con mancuernas', 4, '14 fallo', 90),
        _ex('pdg_remo_menton',    'Remo al mentón en polea', 4, '12', 60),
        _ex('pdg_delt_post_pol',  'Deltoides posterior en polea', 3, '15', 60),
        _ex('pdg_salt_lat_cj',    'Saltos laterales al cajón | Progresión', 2, '10', 30),
        _ex('pdg_core_mcgill',    'Core | McGill crunch', 2, '16', 30),
        _ex('pdg_samurai_banded', 'Samurai banded pulls', 2, '20', 30),
      ],
      6: [
        _ex('pdg_hiit_sq_knee',   'HIIT | Sentadilla + toque de rodilla', 3, '30s', 30),
        _ex('pdg_core_knee_toe',  'Core | Knee to toe taps', 3, '30s', 30),
        _ex('pdg_hiit_sprint',    'HIIT | Sprint estático', 3, '30s', 30),
        _ex('pdg_core_kick_sits', 'Core | Kick sits tap', 3, '30s', 30),
        _ex('pdg_hiit_piv_180',   'HIIT | Pivot squat jumps 180°', 3, '30s', 30),
      ]
    },
    // S6 (deload) — sin día 6 (carpeta vacía)
    {
      1: [
        _ex('pdg_m_cat_camel',  'Movilidad | Cat camel', 1, '10', 0),
        _ex('pdg_m_cossak',     'Movilidad | Cossak squat', 1, '8/lado', 0),
        _ex('pdg_m_flex_peso',  'Movilidad | Flexión de tobillo con peso', 1, '30s/lado', 0),
        _ex('pdg_abd_iso',      'Abducción de cadera isométrica con resistencia', 8, '20s iso', 10),
        _ex('pdg_ht_aprox',     'Hip Thrust (aproximación)', 2, '6', 45),
        _ex('pdg_ht',           'Hip Thrust', 3, '8/10', 120),
        _ex('pdg_sq_rebote',    'Sentadilla con rebote', 2, '10', 60),
        _ex('pdg_bulg_mp',      'Sentadilla búlgara en multipower', 3, '8-12', 90),
        _ex('pdg_box_jumps',    'Box jumps | Progresión', 3, '10', 30),
        _ex('pdg_core_pike',    'Core | Pike plank en fitball', 2, '10', 30),
        _ex('pdg_core_kb_wm',   'Core | KB Windmill', 2, '12', 30),
      ],
      2: [
        _ex('pdg_m_snow',        'Movilidad | Prone snow angels', 1, '10', 0),
        _ex('pdg_m_rlunge_r',    'Movilidad | Runners lunge with reach', 1, '6/lado', 0),
        _ex('pdg_m_rot_hum',     'Movilidad | Rotación humeral con peso', 1, '8/lado', 0),
        _ex('pdg_flex_plio',     'Flexiones pliométricas con altura', 3, 'Máximas (12-14)', 60),
        _ex('pdg_jalon_uni',     'Jalón unilateral en polea', 4, '14', 60),
        _ex('pdg_press_hom_uni', 'Press de hombro unilateral', 4, '14', 60),
        _ex('pdg_elev_lat_drop', 'Elevaciones laterales - Drop set', 3, '12', 90),
        _ex('pdg_remo_seal',     'Remo seal', 4, '12', 90),
        _ex('pdg_curl_bic_mc',   'Curl de bíceps con mancuerna', 4, '14', 60),
        _ex('pdg_skull',         'Skull crusher', 4, '14', 60),
        _ex('pdg_liss_torso',    'Cardio LISS', 1, '27 min (5+17+5)', 0),
      ],
      3: [
        _ex('pdg_m_rockback',     'Movilidad | Leg Rockback', 1, '8/lado', 0),
        _ex('pdg_m_standing',     'Movilidad | Standing reach down fwd-back', 1, '6', 0),
        _ex('pdg_hiperext',       'Hiperextensión', 2, '16', 30),
        _ex('pdg_sent_libre_ap',  'Sentadilla libre | barra alta (aproximación)', 2, '6-8', 45),
        _ex('pdg_sent_libre',     'Sentadilla libre | barra alta', 3, '6/8', 75),
        _ex('pdg_pmr_uni_mc',     'Peso muerto rumano unilateral con mancuernas', 2, '12', 90),
        _ex('pdg_skier',          'Skier swings con disco', 3, '12', 60),
        _ex('pdg_pat_glut_pol',   'Patada de glúteo en polea', 3, '14', 90),
        _ex('pdg_curl_femoral',   'Curl de femoral', 3, '14', 90),
        _ex('pdg_soleo_mc',       'Sóleo sentado con mancuernas', 3, '20', 60),
        _ex('pdg_core_pl_inv',    'Core | Plancha inversa con toques de rodilla', 2, '30s', 30),
        _ex('pdg_core_rtwist',    'Core | Russian twist con disco', 3, '20', 30),
      ],
      5: [
        _ex('pdg_ht_uni_sp',      'Hip thrust unilateral sin peso', 3, '14', 0),
        _ex('pdg_pm_sumo_aprox',  'Peso muerto sumo (aproximación)', 2, '4', 30),
        _ex('pdg_pm_sumo',        'Peso muerto sumo', 3, '6/8', 120),
        _ex('pdg_landmine',       'Landmine thruster', 3, '12', 60),
        _ex('pdg_remo_gir_pol',   'Remo gironda en polea', 3, '10-12', 90),
        _ex('pdg_press_banc_mc',  'Press banca inclinado con mancuernas', 4, '14', 90),
        _ex('pdg_remo_menton',    'Remo al mentón en polea', 4, '12', 60),
        _ex('pdg_delt_post_pol',  'Deltoides posterior en polea', 3, '15', 60),
        _ex('pdg_salt_lat_cj',    'Saltos laterales al cajón | Progresión', 2, '10', 30),
        _ex('pdg_samurai_pol',    'Samurai pulls en polea', 2, '16', 60),
        _ex('pdg_core_elev_col',  'Core | Elevación de piernas colgada', 2, '10', 30),
      ]
    },
    // ───── FASE 2 (semanas 7-12, 6 días/sem) ─────
    // S7
    {
      1: [
        _ex('pdg_m_cat_camel',  'Movilidad | Cat camel', 1, '10', 0),
        _ex('pdg_m_cossak',     'Movilidad | Cossak squat', 1, '8/lado', 0),
        _ex('pdg_m_flex_peso',  'Movilidad | Flexión de tobillo con peso', 1, '30s/lado', 0),
        _ex('pdg_abd_res_180',  'Abducción de cadera con resistencia a 180°', 2, '16', 0),
        _ex('pdg_pmr_aprox',    'Peso muerto rumano (aproximación)', 2, '6', 52),
        _ex('pdg_pmr',          'Peso muerto rumano', 3, '8', 90),
        _ex('pdg_rack_kb_sq',   'Rack kettlebell squat', 2, '14', 60),
        _ex('pdg_sq_curtsy',    'Sentadilla + Curtsy lunge con disco', 2, '8', 60),
        _ex('pdg_box_j_rod',    'Box jump desde rodillas | Progresión', 3, '6', 60),
        _ex('pdg_ball_wall',    'Ball wall lateral', 2, '10', 30),
        _ex('pdg_core_pl_dist', 'Core | Plancha con manos distanciadas', 2, '60s', 30),
      ],
      2: [
        _ex('pdg_m_snow',        'Movilidad | Prone snow angels', 1, '10', 0),
        _ex('pdg_m_rlunge_r',    'Movilidad | Runners lunge with reach', 1, '6/lado', 0),
        _ex('pdg_m_rot_hum',     'Movilidad | Rotación humeral con peso', 1, '8/lado', 0),
        _ex('pdg_flex_plio',     'Flexiones pliométricas', 1, 'Máximas (8-10)', 10),
        _ex('pdg_press_banc_mc', 'Press banca con mancuernas', 3, '12', 90),
        _ex('pdg_pullover_pol',  'Pull over en polea', 4, '14', 60),
        _ex('pdg_ball_pushes',   'Ball pushes', 3, '14', 30),
        _ex('pdg_elev_lat_pol',  'Elevaciones laterales en polea', 4, '14', 60),
        _ex('pdg_remo_gir_uni',  'Remo gironda unilateral en polea', 4, '12', 60),
        _ex('pdg_curl_bic_pie',  'Curl de bíceps de pie', 4, '14', 60),
        _ex('pdg_ext_tri_pol',   'Extensión de tríceps en polea', 4, '16', 60),
        _ex('pdg_liss_torso',    'Cardio LISS', 1, '25 min (5+15+5)', 0),
      ],
      3: [
        _ex('pdg_m_flex_rod', 'Movilidad | Flexión de tobillo de rodillas', 1, '10/lado', 0),
        _ex('pdg_m_aduc_kb',  'Movilidad | Aductores con kettlebell', 1, '6/lado', 0),
        _ex('pdg_sent_libre_ap', 'Sentadilla libre | barra alta (aproximación)', 2, '6-8', 52),
        _ex('pdg_sent_libre', 'Sentadilla libre | barra alta', 3, '4/6/8', 90, 'Pirámide'),
        _ex('pdg_glute_br_b', 'Glute bridge con barra', 3, '10', 90),
        _ex('pdg_bulg_goblet','Sentadilla búlgara goblet', 3, '16', 60),
        _ex('pdg_kb_sw_uni',  'Kettlebell swing unilateral', 3, '12', 30),
        _ex('pdg_pull_thru',  'Pull through en polea', 2, '14', 60),
        _ex('pdg_curl_fem_fb','Curl de femoral con fitball', 3, '14', 60),
        _ex('pdg_hiit_drop_sq','HIIT | Drop squats con disco', 3, '12', 30),
        _ex('pdg_core_pl_inv',  'Core | Plancha inversa con toques de rodilla', 2, '30s', 30),
        _ex('pdg_core_rtwist',  'Core | Russian twist con disco', 2, '20', 30),
      ],
      4: [ _ex('pdg_liss_d4', 'Cardio LISS', 1, '25 min', 0, 'Al aire libre — ritmo bajo/moderado') ],
      5: [
        _ex('pdg_gb_uni_sp',    'Glute bridge unilateral sin peso', 2, '14', 0),
        _ex('pdg_sent_sumo',    'Sentadilla sumo', 3, '12', 60),
        _ex('pdg_snatch_disco', 'Snatch con disco', 3, '10', 30),
        _ex('pdg_remo_barra_90','Remo con barra a 90°', 3, '10', 60),
        _ex('pdg_cruce_poleas', 'Cruce de poleas ascendente', 3, '10-12', 60),
        _ex('pdg_elev_lf_mc',   'Elevaciones laterales + frontales con mancuernas', 4, '10', 60),
        _ex('pdg_delt_post_mq', 'Deltoides posterior en máquina', 3, '12', 60),
        _ex('pdg_samurai_pol',  'Samurai pulls en polea', 2, '8', 60),
        _ex('pdg_core_elev_col','Core | Elevación de piernas colgada', 2, '12', 30),
      ],
      6: [
        _ex('pdg_hiit_side2side','HIIT | Side to side bounds', 3, '30s', 30),
        _ex('pdg_hiit_burpee_ns','HIIT | Burpee sin salto', 3, '30s', 30),
        _ex('pdg_hiit_rock_j',   'HIIT | Rocket jump squat taps', 3, '30s', 30),
        _ex('pdg_hiit_bench_j',  'HIIT | Bench over jumps', 3, '30s', 30),
        _ex('pdg_hiit_jj_sb',    'HIIT | Jumping jacks sin brazos', 3, '30s', 30),
      ]
    },
    // S8
    {
      1: [
        _ex('pdg_m_cat_camel',  'Movilidad | Cat camel', 1, '10', 0),
        _ex('pdg_m_cossak',     'Movilidad | Cossak squat', 1, '8/lado', 0),
        _ex('pdg_m_flex_peso',  'Movilidad | Flexión de tobillo con peso', 1, '30s/lado', 0),
        _ex('pdg_abd_res_180',  'Abducción de cadera con resistencia a 180°', 2, '16', 0),
        _ex('pdg_pmr_aprox',    'Peso muerto rumano (aproximación)', 2, '6', 45),
        _ex('pdg_pmr',          'Peso muerto rumano', 3, '6/8', 75),
        _ex('pdg_rack_kb_sq',   'Rack kettlebell squat', 3, '14', 60),
        _ex('pdg_sq_curtsy',    'Sentadilla + Curtsy lunge con disco', 2, '8', 60),
        _ex('pdg_box_j_rod',    'Box jump desde rodillas | Progresión', 3, '6', 60),
        _ex('pdg_core_pike',    'Core | Pike plank en fitball', 2, '12', 30),
        _ex('pdg_core_kb_wm',   'Core | KB Windmill', 2, '14', 30),
      ],
      2: [
        _ex('pdg_m_snow',        'Movilidad | Prone snow angels', 1, '10', 0),
        _ex('pdg_m_rlunge_r',    'Movilidad | Runners lunge with reach', 1, '6/lado', 0),
        _ex('pdg_m_rot_hum',     'Movilidad | Rotación humeral con peso', 1, '8/lado', 0),
        _ex('pdg_flex_plio',     'Flexiones pliométricas', 3, 'Máximas (8-10)', 60),
        _ex('pdg_press_banc_mc', 'Press banca con mancuernas', 3, '12', 90),
        _ex('pdg_pullover_pol',  'Pull over en polea', 4, '14', 60),
        _ex('pdg_ball_pushes',   'Ball pushes', 3, '14', 30),
        _ex('pdg_elev_lat_pol',  'Elevaciones laterales en polea', 4, '14', 60),
        _ex('pdg_remo_gir_uni',  'Remo gironda unilateral en polea', 4, '12', 60),
        _ex('pdg_curl_bic_pie',  'Curl de bíceps de pie', 4, '14', 60),
        _ex('pdg_ext_tri_pol',   'Extensión de tríceps en polea', 4, '16', 60),
        _ex('pdg_liss_torso',    'Cardio LISS', 1, '25 min (5+15+5)', 0),
      ],
      3: [
        _ex('pdg_m_flex_rod', 'Movilidad | Flexión de tobillo de rodillas', 1, '10/lado', 0),
        _ex('pdg_m_aduc_kb',  'Movilidad | Aductores con kettlebell', 1, '6/lado', 0),
        _ex('pdg_sent_libre_ap','Sentadilla libre | barra alta (aproximación)', 2, '6-8', 60),
        _ex('pdg_sent_libre',   'Sentadilla libre | barra alta', 3, '4/6', 105),
        _ex('pdg_glute_br_b',   'Glute bridge con barra', 3, '10', 90),
        _ex('pdg_bulg_goblet',  'Sentadilla búlgara goblet', 3, '16', 60),
        _ex('pdg_kb_sw_uni',    'Kettlebell swing unilateral', 3, '12', 30),
        _ex('pdg_pull_thru',    'Pull through en polea', 2, '14', 60),
        _ex('pdg_curl_fem_fb',  'Curl de femoral con fitball', 3, '14', 60),
        _ex('pdg_hiit_drop_sq', 'HIIT | Drop squats con disco', 3, '12', 30),
        _ex('pdg_core_cr_res',  'Core | Crunch abdominal con resistencia', 2, '18', 30),
        _ex('pdg_core_rolls',   'Core | Rollouts con barra', 3, '8-10', 30),
      ],
      4: [ _ex('pdg_liss_d4', 'Cardio LISS', 1, '30 min', 0, 'Al aire libre') ],
      5: [
        _ex('pdg_gb_uni_sp',     'Glute bridge unilateral sin peso', 2, '14', 0),
        _ex('pdg_sent_sumo',     'Sentadilla sumo', 3, '12', 60),
        _ex('pdg_snatch_disco',  'Snatch con disco', 3, '10', 30),
        _ex('pdg_aus_chinups',   'Australian chin ups', 3, '10', 60),
        _ex('pdg_cruce_poleas',  'Cruce de poleas ascendente', 3, '10-12', 60),
        _ex('pdg_elev_lf_mc',    'Elevaciones laterales + frontales con mancuernas', 4, '10', 60),
        _ex('pdg_delt_post_mq',  'Deltoides posterior en máquina', 3, '12', 60),
        _ex('pdg_core_mcgill',   'Core | McGill crunch', 2, '16', 30),
        _ex('pdg_samurai_banded','Samurai banded pulls', 2, '20', 30),
      ],
      6: [
        _ex('pdg_hiit_side_bound','HIIT | Side bound launches', 3, '30s', 30),
        _ex('pdg_core_jjplank',   'Core | Jumping jacks plank', 3, '30s', 30),
        _ex('pdg_hiit_tuck_j',    'HIIT | Tuck jumps', 3, '30s', 30),
        _ex('pdg_core_kick_sits', 'Core | Kick sits', 3, '30s', 30),
        _ex('pdg_hiit_shuffle',   'HIIT | Shuffle taps', 3, '30s', 30),
      ]
    },
    // S9
    {
      1: [
        _ex('pdg_m_cat_camel',  'Movilidad | Cat camel', 1, '10', 0),
        _ex('pdg_m_cossak',     'Movilidad | Cossak squat', 1, '8/lado', 0),
        _ex('pdg_m_flex_peso',  'Movilidad | Flexión de tobillo con peso', 1, '30s/lado', 0),
        _ex('pdg_abd_res_180',  'Abducción de cadera con resistencia a 180°', 2, '16', 0),
        _ex('pdg_pmr_aprox',    'Peso muerto rumano (aproximación)', 2, '6', 45),
        _ex('pdg_pmr',          'Peso muerto rumano', 3, '6/8', 75),
        _ex('pdg_rack_kb_sq',   'Rack kettlebell squat', 3, '14', 60),
        _ex('pdg_sq_curtsy',    'Sentadilla + Curtsy lunge con disco', 2, '8', 60),
        _ex('pdg_box_j_rod',    'Box jump desde rodillas | Progresión', 3, '8', 30),
        _ex('pdg_ball_wall',    'Ball wall lateral', 2, '10', 30),
        _ex('pdg_core_pl_dist', 'Core | Plancha con manos distanciadas', 2, '60s', 30),
      ],
      2: [
        _ex('pdg_m_snow',        'Movilidad | Prone snow angels', 1, '10', 0),
        _ex('pdg_m_rlunge_r',    'Movilidad | Runners lunge with reach', 1, '6/lado', 0),
        _ex('pdg_m_rot_hum',     'Movilidad | Rotación humeral con peso', 1, '8/lado', 0),
        _ex('pdg_flex_plio',     'Flexiones pliométricas', 4, 'Máximas (8-10)', 60),
        _ex('pdg_press_banc_mc', 'Press banca con mancuernas', 3, '12', 90),
        _ex('pdg_pullover_pol',  'Pull over en polea', 4, '14', 60),
        _ex('pdg_ball_pushes',   'Ball pushes', 3, '16', 30),
        _ex('pdg_elev_lat_pol',  'Elevaciones laterales en polea', 4, '14', 60),
        _ex('pdg_remo_gir_uni',  'Remo gironda unilateral en polea', 4, '12', 60),
        _ex('pdg_curl_bic_pie',  'Curl de bíceps de pie', 4, '14', 60),
        _ex('pdg_ext_tri_pol',   'Extensión de tríceps en polea', 4, '16', 60),
        _ex('pdg_liss_torso',    'Cardio LISS', 1, '25 min (5+15+5)', 0),
      ],
      3: [
        _ex('pdg_m_flex_rod', 'Movilidad | Flexión de tobillo de rodillas', 1, '10/lado', 0),
        _ex('pdg_m_aduc_kb',  'Movilidad | Aductores con kettlebell', 1, '6/lado', 0),
        _ex('pdg_sent_libre_ap','Sentadilla libre | barra alta (aproximación)', 2, '6-8', 60),
        _ex('pdg_sent_libre',   'Sentadilla libre | barra alta', 3, '4', 120),
        _ex('pdg_glute_br_b',   'Glute bridge con barra', 3, '10', 60),
        _ex('pdg_bulg_goblet',  'Sentadilla búlgara goblet', 3, '16', 60),
        _ex('pdg_kb_sw_uni',    'Kettlebell swing unilateral', 3, '12', 30),
        _ex('pdg_pull_thru',    'Pull through en polea', 2, '14', 60),
        _ex('pdg_curl_fem_fb',  'Curl de femoral con fitball', 3, '14', 60),
        _ex('pdg_hiit_drop_sq', 'HIIT | Drop squats con disco', 3, '12', 30),
        _ex('pdg_core_pl_inv',  'Core | Plancha inversa con toques de rodilla', 2, '16', 30),
        _ex('pdg_core_rtwist',  'Core | Russian twist con disco', 2, '20', 30),
      ],
      4: [ _ex('pdg_liss_d4', 'Cardio LISS', 1, '40 min', 0, 'Al aire libre') ],
      5: [
        _ex('pdg_gb_uni_sp',    'Glute bridge unilateral sin peso', 2, '14', 0),
        _ex('pdg_sent_sumo',    'Sentadilla sumo', 3, '12', 60),
        _ex('pdg_snatch_disco', 'Snatch con disco', 3, '10', 30),
        _ex('pdg_remo_barra_90','Remo con barra a 90°', 3, '10', 90),
        _ex('pdg_cruce_poleas', 'Cruce de poleas ascendente', 3, '10-12', 60),
        _ex('pdg_elev_lf_mc',   'Elevaciones laterales + frontales con mancuernas', 4, '10', 60),
        _ex('pdg_delt_post_mq', 'Deltoides posterior en máquina', 3, '12', 60),
        _ex('pdg_samurai_pol',  'Samurai pulls en polea', 2, '16', 60),
        _ex('pdg_core_elev_col','Core | Elevación de piernas colgada', 2, '12', 30),
      ],
      6: [
        _ex('pdg_hiit_lat_jp',    'HIIT | Lunge lateral jump', 3, '30s', 30),
        _ex('pdg_core_drunk_mt',  'Core | Drunken mountain climbers', 3, '30s', 30),
        _ex('pdg_hiit_sprint_res','HIIT | Sprints con resistencia', 3, '30s', 30),
        _ex('pdg_hiit_walk_piv',  'HIIT | Walking pivot squats', 3, '30s', 30),
        _ex('pdg_hiit_jumping_j', 'HIIT | Jumping jacks', 3, '30s', 30),
      ]
    },
    // S10
    {
      1: [
        _ex('pdg_m_cat_camel',  'Movilidad | Cat camel', 1, '10', 0),
        _ex('pdg_m_cossak',     'Movilidad | Cossak squat', 1, '8/lado', 0),
        _ex('pdg_m_flex_peso',  'Movilidad | Flexión de tobillo con peso', 1, '30s/lado', 0),
        _ex('pdg_abd_res_180',  'Abducción de cadera con resistencia a 180°', 2, '16', 0),
        _ex('pdg_pmr_aprox',    'Peso muerto rumano (aproximación)', 2, '6', 60),
        _ex('pdg_pmr',          'Peso muerto rumano', 3, '6/8', 75),
        _ex('pdg_rack_kb_sq',   'Rack kettlebell squat', 3, '14', 60),
        _ex('pdg_sq_curtsy',    'Sentadilla + Curtsy lunge con disco', 3, '8', 60),
        _ex('pdg_box_j_rod',    'Box jump desde rodillas | Progresión', 3, '8', 60),
        _ex('pdg_core_pike',    'Core | Pike plank en fitball', 2, '12', 30),
        _ex('pdg_core_kb_wm',   'Core | KB Windmill', 2, '12', 30),
      ],
      2: [
        _ex('pdg_m_snow',        'Movilidad | Prone snow angels', 1, '10', 0),
        _ex('pdg_m_rlunge_r',    'Movilidad | Runners lunge with reach', 1, '6/lado', 0),
        _ex('pdg_m_rot_hum',     'Movilidad | Rotación humeral con peso', 1, '8/lado', 0),
        _ex('pdg_flex_plio',     'Flexiones pliométricas', 4, 'Máximas (10-12)', 0),
        _ex('pdg_press_banc_mc', 'Press banca con mancuernas', 4, '12', 90),
        _ex('pdg_pullover_pol',  'Pull over en polea', 4, '14', 60),
        _ex('pdg_ball_pushes',   'Ball pushes', 3, '16', 30),
        _ex('pdg_elev_lat_pol',  'Elevaciones laterales en polea', 4, '14', 60),
        _ex('pdg_remo_gir_uni',  'Remo gironda unilateral en polea', 4, '12', 60),
        _ex('pdg_curl_bic_pie',  'Curl de bíceps de pie', 4, '14', 60),
        _ex('pdg_ext_tri_pol',   'Extensión de tríceps en polea', 4, '16', 60),
        _ex('pdg_liss_torso',    'Cardio LISS', 1, '25 min (5+15+5)', 0),
      ],
      3: [
        _ex('pdg_m_flex_rod', 'Movilidad | Flexión de tobillo de rodillas', 1, '10/lado', 0),
        _ex('pdg_m_aduc_kb',  'Movilidad | Aductores con kettlebell', 1, '6/lado', 0),
        _ex('pdg_sent_libre_ap','Sentadilla libre | barra alta (aproximación)', 2, '6-8', 45),
        _ex('pdg_sent_libre',   'Sentadilla libre | barra alta', 3, '4/6', 105),
        _ex('pdg_glute_br_b',   'Glute bridge con barra', 3, '10', 60),
        _ex('pdg_bulg_goblet',  'Sentadilla búlgara goblet', 3, '16', 60),
        _ex('pdg_kb_sw_uni',    'Kettlebell swing unilateral', 3, '12', 30),
        _ex('pdg_pull_thru',    'Pull through en polea', 2, '14', 60),
        _ex('pdg_curl_fem_fb',  'Curl de femoral con fitball', 3, '14', 60),
        _ex('pdg_hiit_drop_sq', 'HIIT | Drop squats con disco', 3, '12', 30),
        _ex('pdg_core_cr_res',  'Core | Crunch abdominal con resistencia', 2, '18', 30),
        _ex('pdg_core_rolls',   'Core | Rollouts con barra', 3, '10', 30),
      ],
      4: [ _ex('pdg_liss_d4', 'Cardio LISS', 1, '45 min', 0, 'Al aire libre') ],
      5: [
        _ex('pdg_gb_uni_sp',   'Glute bridge unilateral sin peso', 2, '14', 0),
        _ex('pdg_sent_sumo',   'Sentadilla sumo', 3, '12', 60),
        _ex('pdg_snatch_disco','Snatch con disco', 3, '10', 30),
        _ex('pdg_aus_chinups', 'Australian chin ups', 3, '12', 60),
        _ex('pdg_cruce_poleas','Cruce de poleas ascendente', 3, '10-12', 60),
        _ex('pdg_elev_lf_mc',  'Elevaciones laterales + frontales con mancuernas', 4, '10', 60),
        _ex('pdg_delt_post_mq','Deltoides posterior en máquina', 3, '12', 60),
        _ex('pdg_core_mcgill', 'Core | McGill crunch', 2, '16', 30),
        _ex('pdg_samurai_banded','Samurai banded pulls', 2, '20', 30),
      ],
      6: [
        _ex('pdg_hiit_piv_360',   'HIIT | Pivot squat jumps 360°', 3, '30s', 30),
        _ex('pdg_hiit_burpees',   'HIIT | Burpees', 3, '30s', 30),
        _ex('pdg_hiit_side2side', 'HIIT | Side to side bounds', 3, '30s', 30),
        _ex('pdg_core_fwd_kick',  'Core | Forward kick sits', 3, '30s', 30),
        _ex('pdg_hiit_fast_feet', 'HIIT | Fast feet', 3, '30s', 30),
      ]
    },
    // S11
    {
      1: [
        _ex('pdg_m_cat_camel',  'Movilidad | Cat camel', 1, '10', 0),
        _ex('pdg_m_cossak',     'Movilidad | Cossak squat', 1, '8/lado', 0),
        _ex('pdg_m_flex_peso',  'Movilidad | Flexión de tobillo con peso', 1, '30s/lado', 0),
        _ex('pdg_abd_res_180',  'Abducción de cadera con resistencia a 180°', 2, '16', 0),
        _ex('pdg_pmr_aprox',    'Peso muerto rumano (aproximación)', 2, '6', 45),
        _ex('pdg_pmr',          'Peso muerto rumano', 3, '6/8', 105),
        _ex('pdg_rack_kb_sq',   'Rack kettlebell squat', 3, '14', 60),
        _ex('pdg_sq_curtsy',    'Sentadilla + Curtsy lunge con disco', 3, '8', 60),
        _ex('pdg_box_j_rod',    'Box jump desde rodillas | Progresión', 3, '8', 60),
        _ex('pdg_ball_wall',    'Ball wall lateral', 2, '10', 30),
        _ex('pdg_core_pl_dist', 'Core | Plancha con manos distanciadas', 2, '60s', 30),
      ],
      2: [
        _ex('pdg_m_snow',        'Movilidad | Prone snow angels', 1, '10', 0),
        _ex('pdg_m_rlunge_r',    'Movilidad | Runners lunge with reach', 1, '6/lado', 0),
        _ex('pdg_m_rot_hum',     'Movilidad | Rotación humeral con peso', 1, '8/lado', 0),
        _ex('pdg_flex_plio',     'Flexiones pliométricas', 4, 'Máximas (10-12)', 0),
        _ex('pdg_press_banc_mc', 'Press banca con mancuernas', 4, '12', 90),
        _ex('pdg_pullover_pol',  'Pull over en polea', 4, '14', 60),
        _ex('pdg_ball_pushes',   'Ball pushes', 3, '16', 30),
        _ex('pdg_elev_lat_pol',  'Elevaciones laterales en polea', 4, '14', 60),
        _ex('pdg_remo_gir_uni',  'Remo gironda unilateral en polea', 4, '12', 60),
        _ex('pdg_curl_bic_pie',  'Curl de bíceps de pie', 4, '14', 60),
        _ex('pdg_ext_tri_pol',   'Extensión de tríceps en polea', 4, '16', 60),
        _ex('pdg_liss_torso',    'Cardio LISS', 1, '25 min (5+15+5)', 0),
      ],
      3: [
        _ex('pdg_m_flex_rod', 'Movilidad | Flexión de tobillo de rodillas', 1, '10/lado', 0),
        _ex('pdg_m_aduc_kb',  'Movilidad | Aductores con kettlebell', 1, '6/lado', 0),
        _ex('pdg_sent_libre_ap','Sentadilla libre | barra alta (aproximación)', 2, '6', 45),
        _ex('pdg_sent_libre',   'Sentadilla libre | barra alta', 3, '4/6', 90),
        _ex('pdg_glute_br_b',   'Glute bridge con barra', 3, '10', 60),
        _ex('pdg_bulg_goblet',  'Sentadilla búlgara goblet', 3, '16', 60),
        _ex('pdg_kb_sw_uni',    'Kettlebell swing unilateral', 3, '12', 60),
        _ex('pdg_pull_thru',    'Pull through en polea', 2, '14', 60),
        _ex('pdg_curl_fem_fb',  'Curl de femoral con fitball', 3, '14', 60),
        _ex('pdg_hiit_drop_sq', 'HIIT | Drop squats con disco', 3, '12', 30),
        _ex('pdg_core_pl_inv',  'Core | Plancha inversa con toques de rodilla', 2, '30s', 30),
        _ex('pdg_core_rtwist',  'Core | Russian twist con disco', 3, '20', 30),
      ],
      4: [ _ex('pdg_liss_d4', 'Cardio LISS', 1, '45 min', 0, 'Al aire libre') ],
      5: [
        _ex('pdg_gb_uni_sp',    'Glute bridge unilateral sin peso', 2, '14', 0),
        _ex('pdg_sent_sumo',    'Sentadilla sumo', 3, '12', 60),
        _ex('pdg_snatch_disco', 'Snatch con disco', 3, '10', 30),
        _ex('pdg_remo_barra_90','Remo con barra a 90°', 3, '10', 90),
        _ex('pdg_cruce_poleas', 'Cruce de poleas ascendente', 3, '10-12', 60),
        _ex('pdg_elev_lf_mc',   'Elevaciones laterales + frontales con mancuernas', 4, '10', 60),
        _ex('pdg_delt_post_mq', 'Deltoides posterior en máquina', 3, '12', 60),
        _ex('pdg_core_rolls',   'Core | Rollouts con barra', 2, '8', 30),
      ],
      6: [
        _ex('pdg_hiit_sq_toes', 'HIIT | Sentadilla + toques de pie', 3, '30s', 30),
        _ex('pdg_hiit_burpees', 'HIIT | Burpees', 3, '30s', 30),
        _ex('pdg_hiit_pulse_lu','HIIT | Pulse lunges', 3, '30s', 30),
        _ex('pdg_hiit_calf',    'HIIT | Calf jumps', 3, '30s', 30),
        _ex('pdg_hiit_expl_jj', 'HIIT | Explosive jumping jacks', 3, '30s', 30),
      ]
    },
    // S12 (deload)
    {
      1: [
        _ex('pdg_m_cat_camel',  'Movilidad | Cat camel', 1, '10', 0),
        _ex('pdg_m_cossak',     'Movilidad | Cossak squat', 1, '8/lado', 0),
        _ex('pdg_m_flex_peso',  'Movilidad | Flexión de tobillo con peso', 1, '30s/lado', 0),
        _ex('pdg_abd_res_180',  'Abducción de cadera con resistencia a 180°', 2, '16', 0),
        _ex('pdg_pmr_aprox',    'Peso muerto rumano (aproximación)', 2, '6', 45),
        _ex('pdg_pmr',          'Peso muerto rumano', 3, '6/8', 105),
        _ex('pdg_rack_kb_sq',   'Rack kettlebell squat', 3, '14', 60),
        _ex('pdg_sq_curtsy',    'Sentadilla + Curtsy lunge con disco', 3, '8', 60),
        _ex('pdg_box_j_rod',    'Box jump desde rodillas | Progresión', 3, '8', 60),
        _ex('pdg_core_pike',    'Core | Pike plank en fitball', 2, '12', 30),
        _ex('pdg_core_kb_wm',   'Core | KB Windmill', 2, '12', 30),
      ],
      2: [
        _ex('pdg_m_snow',        'Movilidad | Prone snow angels', 1, '10', 0),
        _ex('pdg_m_rlunge_r',    'Movilidad | Runners lunge with reach', 1, '6/lado', 0),
        _ex('pdg_m_rot_hum',     'Movilidad | Rotación humeral con peso', 1, '8/lado', 0),
        _ex('pdg_flex_plio',     'Flexiones pliométricas', 4, 'Máximas (10-12)', 60),
        _ex('pdg_press_banc_mc', 'Press banca con mancuernas', 4, '12', 90),
        _ex('pdg_pullover_pol',  'Pull over en polea', 4, '14', 60),
        _ex('pdg_ball_pushes',   'Ball pushes', 3, '16', 30),
        _ex('pdg_elev_lat_pol',  'Elevaciones laterales en polea', 4, '14', 60),
        _ex('pdg_remo_gir_uni',  'Remo gironda unilateral en polea', 4, '12', 60),
        _ex('pdg_curl_bic_pie',  'Curl de bíceps de pie', 4, '14', 60),
        _ex('pdg_ext_tri_pol',   'Extensión de tríceps en polea', 4, '16', 60),
        _ex('pdg_liss_torso',    'Cardio LISS', 1, '25 min (5+15+5)', 0),
      ],
      3: [
        _ex('pdg_m_flex_rod', 'Movilidad | Flexión de tobillo de rodillas', 1, '10/lado', 0),
        _ex('pdg_m_aduc_kb',  'Movilidad | Aductores con kettlebell', 1, '6/lado', 0),
        _ex('pdg_sent_libre_ap','Sentadilla libre | barra alta (aproximación)', 2, '6', 60),
        _ex('pdg_sent_libre',   'Sentadilla libre | barra alta', 3, '4-6', 120),
        _ex('pdg_glute_br_b',   'Glute bridge con barra', 3, '10', 60),
        _ex('pdg_bulg_goblet',  'Sentadilla búlgara goblet', 3, '16', 60),
        _ex('pdg_kb_sw_uni',    'Kettlebell swing unilateral', 3, '12', 60),
        _ex('pdg_pull_thru',    'Pull through en polea', 2, '14', 60),
        _ex('pdg_curl_fem_fb',  'Curl de femoral con fitball', 3, '14', 60),
        _ex('pdg_hiit_drop_sq', 'HIIT | Drop squats con disco', 3, '12', 30),
        _ex('pdg_core_cr_res',  'Core | Crunch abdominal con resistencia', 2, '16', 30),
        _ex('pdg_core_rolls',   'Core | Rollouts con barra', 3, '10', 30),
      ],
      4: [ _ex('pdg_liss_d4', 'Cardio LISS', 1, '45 min', 0, 'Al aire libre') ],
      5: [
        _ex('pdg_gb_uni_sp',    'Glute bridge unilateral sin peso', 2, '14', 0),
        _ex('pdg_sent_sumo',    'Sentadilla sumo', 3, '12', 60),
        _ex('pdg_snatch_disco', 'Snatch con disco', 3, '10', 30),
        _ex('pdg_aus_chinups',  'Australian chin ups', 3, '14', 75),
        _ex('pdg_cruce_poleas', 'Cruce de poleas ascendente', 3, '10-12', 60),
        _ex('pdg_elev_lf_mc',   'Elevaciones laterales + frontales con mancuernas', 4, '10', 60),
        _ex('pdg_delt_post_mq', 'Deltoides posterior en máquina', 3, '12', 60),
        _ex('pdg_core_rolls',   'Core | Rollouts con barra', 2, '8', 30),
      ],
      6: [
        _ex('pdg_hiit_lunge_jp',  'HIIT | Lunge jump', 3, '30s', 30),
        _ex('pdg_core_jjtap_plk', 'Core | Jumping jacks taps plank', 3, '30s', 30),
        _ex('pdg_hiit_sq_paso',   'HIIT | Sentadilla + paso atrás', 3, '30s', 30),
        _ex('pdg_core_knee_toe',  'Core | Knee to toe taps', 3, '30s', 30),
        _ex('pdg_hiit_thrust_res','HIIT | Thrusters con resistencia', 3, '30s', 30),
      ]
    }
  ]
};
